### PR TITLE
fix(Clarity2):Factor out 'stx-transfer-memo' into a separate function

### LINKED ISSUE #2615: Extension contract: stx-transfer-memo?
In Stacks 2.1 right now, `stx-transfer?` can take an optional memo field.  Unfortunately, the presence of this change would mean the parser would need to be aware of the epoch rules in order to know which invocations are allowed.

Instead of doing this, I propose refactoring `stx-transfer?` in 2.1 into an extension contract with the public function `stx-transfer-memo?`.  This would do the same things that `stx-transfer` does, but would use the epoch-switching gates that already would exist for all extension contracts (and wouldn't require modifying the analysis logic).

Open to push-back on this.

### PR DESCRIPTION
**Pull request by gregorycoppola**
Fixes #2615

## Motivation
Currently, in the next branch, it is possible to supply a memo to `stx-transfer?`. However, it has been decided that it might be better to force the user to use a *different* function,`stx-transfer-memo?` if they are going to add a memo. The reason for this is to allow better type checking -- the user will either have to add a memo or not, depending on which version of the function they use, and they won't be able to forget to put a memo if they are using the "memo" version.

We also version-guard this function, so that one has to be using Stacks 2.1 in order to use it.

## Testing

Tested using unit tests. The following tests have been modified:

```
M	src/vm/analysis/arithmetic_checker/tests.rs
M	src/vm/analysis/type_checker/tests/mod.rs
M	src/vm/tests/costs.rs
M	src/vm/tests/events.rs
M	src/vm/tests/simple_apply_eval.rs
```

### CODE REVIEW

File: src/vm/analysis/type_checker/tests/mod.rs [hunk 1]
```diff
@@ -188,26 +188,24 @@ fn test_stx_ops() {
...
         r#"(stx-transfer? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 0x7759)"#,
-        r#"(stx-transfer? 4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 0x000000)"#,
+        r#"(stx-transfer? 4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR)"#,
         r#"(stx-transfer? 4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR true 0x00)"#,
-        r#"(stx-transfer? u4 u3  'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 0x00)"#,
-        r#"(stx-transfer? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR true 0x00)"#,
-        r#"(stx-transfer? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR true)"#,
-        "(stx-transfer? u10 tx-sponsor? 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G)",
+        r#"(stx-transfer? u4 u3  'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR)"#,
+        r#"(stx-transfer? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR true)"#,
```
Comment (kantai) [inline src/vm/analysis/type_checker/tests/mod.rs:201]: Can you add two new tests for:

```
(stx-transfer? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G 0x000000)
(stx-transfer-memo? u4 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G)
```

i.e., make sure that the two functions don't accept one another's inputs.

**Review by kantai — APPROVED** [review]
LGTM! Just commented about a small test addition.

File: src/vm/analysis/type_checker/tests/mod.rs (hunk 1 above)
Comment (gregorycoppola) [reply src/vm/analysis/type_checker/tests/mod.rs:206]: done

**Review by gregorycoppola — COMMENTED** [review]
thanks for review!

File: src/vm/costs/cost_functions.rs [hunk 2]
```diff
@@ -120,6 +120,7 @@ define_named_enum!(ClarityCostFunction {
     BlockInfo("cost_block_info"),
     StxBalance("cost_stx_balance"),
     StxTransfer("cost_stx_transfer"),
+    StxTransferMemo("cost_stx_transfer"),
```
Comment (jcnelson) [inline src/vm/costs/cost_functions.rs:123]: Should this be `unimplemented` for now?

File: src/vm/functions/assets.rs [hunk 3]
```diff
@@ -147,24 +147,40 @@ pub fn special_stx_transfer(
...
+        Err(CheckErrors::BadTransferSTXArguments.into())
     }
+}
 
+pub fn special_stx_transfer_memo(
+    args: &[SymbolicExpression],
+    env: &mut Environment,
+    context: &LocalContext,
+) -> Result<Value> {
+    check_argument_count(4, args)?;
```
Comment (jcnelson) [inline src/vm/functions/assets.rs:177]: This has the wrong cost function -- it should be `StxTransferMemo`.

**Review by jcnelson — CHANGES_REQUESTED** [review]
I didn't see any gating for `stx-transfer-memo?`.  I think you'll want to add that in first before merging -- `stx-transfer-memo?` is not valid in Clarity 1.

File: src/vm/functions/assets.rs (hunk 3 above)
Comment (gregorycoppola) [reply src/vm/functions/assets.rs:177]: replaced with Unimplemented

File: src/vm/costs/cost_functions.rs (hunk 2 above)
Comment (gregorycoppola) [reply src/vm/costs/cost_functions.rs]: this line is gone because I used Unimplemented in src/vm/functions/assets.rs

File: src/vm/analysis/arithmetic_checker/tests.rs [hunk 4]
```diff
@@ -130,95 +130,123 @@ fn test_variables_fail_arithmetic_check() {
 }
 
 #[test]
-fn test_functions() {
-    let bad_tests = [
+fn test_functions_clarity1() {
```
Comment (gregorycoppola) [inline src/vm/analysis/arithmetic_checker/tests.rs:133]: note: I separated these tests into "clarity1" and "clarity2", similar to what was suggested in https://github.com/blockstack/stacks-blockchain/pull/2735

File: src/vm/functions/mod.rs [hunk 5]
```diff
@@ -138,6 +138,7 @@ define_versioned_named_enum!(NativeFunctions(ClarityVersion) {
     BurnAsset("nft-burn?", ClarityVersion::Clarity1),
     GetStxBalance("stx-get-balance", ClarityVersion::Clarity1),
     StxTransfer("stx-transfer?", ClarityVersion::Clarity1),
+    StxTransferMemo("stx-transfer-memo?", ClarityVersion::Clarity2),
```
Comment (gregorycoppola) [inline src/vm/functions/mod.rs:141]: note: version guarding here

**Review by gregorycoppola — COMMENTED** [review]
@jcnelson  thanks for the comments.

I rebased against 'next' so now this PR has version guarding. 

Refactored tests in `src/vm/analysis/arithmetic_checker/tests.rs` test the version guarding.

File: src/vm/analysis/arithmetic_checker/tests.rs (hunk 4 above)
Comment (jcnelson) [reply src/vm/analysis/arithmetic_checker/tests.rs:133]: Thanks for doing this -- I think it's a healthy habit to maintain, especially since there will likely be future versions of Clarity.

**Review by jcnelson — COMMENTED** [review]
LGTM now. Thanks @gregorycoppola!

**Review by jcnelson — APPROVED** [review]

**Comment by gregorycoppola** [comment]
Thanks for the reviews everyone.
