### PR TITLE
Fix/5230

### LINKED ISSUE #5230: [Bug] burn ops are applied multiple times per tenure
This code is buggy:

```rust
        let (stacking_burn_ops, transfer_burn_ops, delegate_burn_ops, vote_for_agg_key_ops) =
            if new_tenure || tenure_extend {
                StacksChainState::get_stacking_and_transfer_and_delegate_burn_ops(
                    chainstate_tx,
                    &parent_index_hash,
                    sortition_dbconn.sqlite_conn(),
                    &burn_header_hash,
                    burn_header_height.into(),
                )?
            } else {
                (vec![], vec![], vec![], vec![])
            };
```

We should only be loading up the on-burnchain operations if the burn view has changed.  This neither corresponds to tenure-change nor tenure-extend blocks.

### PR DESCRIPTION
**Pull request by jcnelson**
Fixes #5230 by indexing Stacks-on-Bitcoin operations by the tenure-start block ID, instead of each and every Stacks block.

Leaving as a draft for now until I can write more unit tests.

### CODE REVIEW

**Review by kantai — COMMENTED** [review]
This looks good to me -- will re-review when tests are added.

File: testnet/stacks-node/src/tests/nakamoto_integrations.rs [hunk 1]
```diff
@@ -4378,7 +4539,8 @@ fn stack_stx_burn_op_integration_test() {
         stack_stx_burn_op_tx_count, 1,
         "Stack-stx tx without a signer_key shouldn't have been submitted"
     );
-
+    assert!(transfer_stx_found, "Expected transfer STX op");
+    assert!(delegate_stx_found, "Expected delegate STX op");
```
Comment (jcnelson) [inline testnet/stacks-node/src/tests/nakamoto_integrations.rs:4543]: Thanks for the extra test coverage @hstove!

**Review by kantai — DISMISSED** [review]

**Review by kantai — APPROVED** [review]

**Review by saralab — APPROVED** [review]

**Review by obycode — APPROVED** [review]
LGTM!
