### PR TITLE
Fix/5249

### LINKED ISSUE #5249: [Network] Inventory cache incoherency
For reasons that are not yet clear to me, nodes' cached tenure data will eventually become inconsistent with tenures stored in the Nakamoto chain state.  This, in turn, causes them to produce invalid `NakamotoInv` messages, which prevents downstream peers from finding and downloading tenures.

### PR DESCRIPTION
**Pull request by jcnelson**
Fixes #5249. The bug was that we were not invalidating cached negatives (i.e. marking the absence of a tenure) when the Nakamoto tip advanced.  As a result, tenures that did not yet exist as of the Nakamoto tip when the cache was initially populated, but later came into existence, would never be reported in the inventory vector.

Leaving this as a draft until I can add some more test coverage.

### CODE REVIEW

**Comment by jcnelson** [comment]
Don't let the line count scare you. The fix is very small; over 90% of the new lines are tests.

File: stackslib/src/main.rs [hunk 1]
```diff
@@ -974,6 +975,61 @@ simulating a miner.
...
+            let sn = SortitionDB::get_block_snapshot_consensus(
+                sortition_db.conn(),
+                &header.consensus_hash,
+            )
+            .unwrap()
+            .unwrap();
+
+            let reward_cycle = sortition_db
+                .pox_constants
+                .block_height_to_reward_cycle(230, sn.block_height)
```
Comment (jferrant) [inline stackslib/src/main.rs:1008]: Should 230 be put into a variable?

File: stackslib/src/main.rs [hunk 2]
```diff
@@ -974,6 +975,61 @@ simulating a miner.
...
+    if argv[1] == "get-tenure-inv" {
+        let chainstate_root_path = &argv[2];
+        let tip_block_ids = &argv[3..];
+        let chainstate_path = format!("{}/chainstate", &chainstate_root_path);
+        let sortition_path = format!("{}/burnchain/sortition", &chainstate_root_path);
+
+        let (chainstate, _) =
+            StacksChainState::open(false, 0x80000000, &chainstate_path, None).unwrap();
+        let pox_consts =
+            PoxConstants::new(900, 100, 80, 0, 0, u64::MAX, u64::MAX, 240, 241, 242, 242);
```
Comment (kantai) [inline stackslib/src/main.rs:987]: This is a lot of magic numbers

File: stackslib/src/main.rs (hunk 1 above)
Comment (jcnelson) [reply stackslib/src/main.rs:1008]: This is a one-off tool that I wrote to test this against the live nakamoto testnet.  I'm fine with just dropping the patch to this file.

File: stackslib/src/main.rs (hunk 2 above)
Comment (jcnelson) [reply stackslib/src/main.rs:987]: This is a one-off tool that I wrote to test this against the live nakamoto testnet. I'm fine with just dropping the patch to this file.

File: stackslib/src/main.rs [hunk 3]
```diff
@@ -974,6 +975,61 @@ simulating a miner.
...
 
+    if argv[1] == "get-tenure-inv" {
+        let chainstate_root_path = &argv[2];
+        let tip_block_ids = &argv[3..];
+        let chainstate_path = format!("{}/chainstate", &chainstate_root_path);
+        let sortition_path = format!("{}/burnchain/sortition", &chainstate_root_path);
+
+        let (chainstate, _) =
+            StacksChainState::open(false, 0x80000000, &chainstate_path, None).unwrap();
+        let pox_consts =
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/main.rs:986]: This is a one-off tool that I wrote to test this against the live nakamoto testnet. I'm fine with just dropping the patch to this file.

File: stackslib/src/net/inv/nakamoto.rs [hunk 4]
```diff
@@ -188,23 +220,30 @@ impl InvGenerator {
...
                     .processed_tenures
                     .remove(&ancestor_tip_id)
                     .unwrap_or_else(|| {
                         panic!("FATAL: did not have ancestor tip reported by search");
                     });
 
+                for ch in intermediate_tenures.into_iter() {
+                    ancestor_tenures.remove(&ch);
+                }
+                ancestor_tenures.remove(tip_block_ch);
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/net/inv/nakamoto.rs:245]: Each entry in `ancestor_tenures` is an `InvTenureInfo`, which contains the `tenure_id_consensus_hash` and `parent_tenure_id_consensus_hash` for the given key (i.e. `ch in intermediate_tenures` and `tip_block_ch`).  Removing them is important, because it prevents caching the _absence_ of a tenure after it has arrived (which is the bug that's being fixed here).

Whenever the function `make_tenure_bitvector` is called on a cold cache, the code will walk the tenure history for the given Stacks tip's reward cycle and generate an `Option<InvTenureInfo>` struct for each sortition.  It will be `None` for a given sortition's consensus hash if either (1) there is no sortition, or (2) there are no Stacks blocks for that tenure.  Importantly, condition (2) can change with the arrival of new Stacks blocks, so we need to evict affected entries in `processed_tenures` when that happens.  We weren't doing this.

This code relies on the fact that a change to the value of a `PeerNetwork`'s `StacksTipInfo` instance, which caches the Stacks chain tip, would imply that new blocks have arrived and been processed since the last call to `make_tenure_bitvector`.  This in turn means that some new blocks have been processed, and some entries in `processed_tenures` need to be evicted since they would now incorrectly report a `None` for a tenure of blocks we processed.

The eviction code here works by looking at all of the tenures in-between the highest cached ancestor of the chain tip and the given chain tip, and if there are any, clearing out their associated `Option<InvTenureInfo>` since the tip advanced past that tenure's boundary.

[the remark this answers is not in the document]
Comment (kantai) [reply stackslib/src/net/inv/nakamoto.rs:245]: > This code relies on the fact that a change to the value of a PeerNetwork's StacksTipInfo instance, which caches the Stacks chain tip, would imply that new blocks have arrived and been processed since the last call to make_tenure_bitvector. This in turn means that some new blocks have been processed, and some entries in processed_tenures need to be evicted since they would now incorrectly report a None for a tenure of blocks we processed.

Ah, okay. This cache maintenance logic needs to be documented in the code comments. 

> The eviction code here works by looking at all of the tenures in-between the highest cached ancestor of the chain tip and the given chain tip, and if there are any, clearing out their associated Option<InvTenureInfo> since the tip advanced past that tenure's boundary.

I think its also important to mention that it must invalidate _inclusively_: i.e., the highest cached ancestor itself must also be invalidated. I think this patch does that, but it needs to be made clear when you document the cache maintenance.

[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/net/inv/nakamoto.rs:245]: > This cache maintenance logic needs to be documented in the code comments.

Can do :+1: 

> I think its also important to mention that it must invalidate inclusively: i.e., the highest cached ancestor itself must also be invalidated. I think this patch does that, but it needs to be made clear when you document the cache maintenance.

This happens.  The code for `find_ancestor_processed_tenures()` is guaranteed to return the given tip's tenure ID in its vector of tenure IDs, if it returns anything at all, since the tenure ID for the tip is unconditionally loaded and pushed to that vector before the ancestor search.

**Review by obycode — APPROVED** [review]
LGTM

**Review by jferrant — APPROVED** [review]

**Comment by jferrant** [comment]
I think this is okay, but i have never seen tests::nakamoto_integrations::continue_tenure_extend fail before so wonder if its an issue with this branch...

File: stackslib/src/net/inv/nakamoto.rs [hunk 5]
```diff
@@ -113,6 +113,8 @@ pub struct InvGenerator {
     tip_ancestor_search_depth: u64,
     /// count cache misses for `processed_tenures`
     cache_misses: u128,
+    /// Disable caching (test only)
+    no_cache: bool,
```
Comment (hstove) [inline stackslib/src/net/inv/nakamoto.rs:117]: For safety, should we put this behind a `#[cfg(test)]` flag?

Comment (jcnelson) [reply stackslib/src/net/inv/nakamoto.rs:117]: Sure

File: stackslib/src/main.rs [hunk 6]
```diff
@@ -974,6 +1142,28 @@ simulating a miner.
...
+        // send getnakamotoinv
+        let get_nakamoto_inv =
+            StacksMessageType::GetNakamotoInv(GetNakamotoInvData { consensus_hash: ch });
+
+        let msg = session.make_peer_message(get_nakamoto_inv).unwrap();
+        session.send_peer_message(msg).unwrap();
+        let resp = session.recv_peer_message().unwrap();
+
+        let StacksMessageType::NakamotoInv(inv) = &resp.payload else {
+            panic!("Got spurious message: {:?}", &resp);
```
Comment (hstove) [inline stackslib/src/main.rs:1161]: When I run this, targeted at my naka node, I get:

```
Got spurious message: StacksMessage { preamble: Preamble { peer_version: 4207599114, network_id: 2147483648, seq: 4167833110, burn_block_height: 75190, burn_block_hash: 3e6d9605bdddaa22b6497ee6e518bdea631512c76180a277cdcdb9d3b25b94f1, burn_stable_block_height: 75189, burn_stable_block_hash: 69accdd0003b8f6c8d522066e3f556a7a00fb0af206c9140e42a1c746ad4f89e, additional_data: 0, signature: 0035998ea0a3a63681150f5788ee02f3e68ef76b1a3520d1dbb869babe4bf462612838b6f84d43693274f4af54a4d489d53806b56ed064896bd6aecf5cb541672e, payload_len: 269 }, relayers: [RelayData { peer: e728418423378cf56244712f0bb5983b2d84f1cf://34.150.184.50:20444, seq: 0 }, RelayData { peer: 98d81b3c2c991fe51710a7ea329e4ae1e77f8068://34.150.184.50:20444, seq: 0 }], payload: Transaction(StacksTransaction { version: Testnet, chain_id: 2147483648, auth: Standard(Singlesig(SinglesigSpendingCondition { hash_mode: P2PKH, signer: e959844d85de7954970675332446df1c5a54419c, nonce: 8652, tx_fee: 300, key_encoding: Compressed, signature: 009821ecf87a26b5662cba9112ff5f3a95799533301d6f4886079042ef8471af0e3860f4655f383ee9ebddff144eb6db408354ecf53f21e3133faf4fe5e8ac7d90 })), anchor_mode: Any, post_condition_mode: Deny, post_conditions: [], payload: TokenTransfer(Standard(StandardPrincipalData(ST484MS3VACPAZ90WHC21XQ7T6XANCV341HJYE0W)), 1000, 00000000000000000000000000000000000000000000000000000000000000000000) }) }
```

Is this expected? Note that I just used the `pox_consensus` I got from `/v2/info`.

File: stackslib/src/main.rs [hunk 7]
```diff
@@ -974,6 +1142,28 @@ simulating a miner.
         process::exit(1);
     }
 
+    if argv[1] == "getnakamotoinv" {
```
Comment (hstove) [inline stackslib/src/main.rs:1145]: Nit: please add

```
        if argv.len() < 5 {
            eprintln!("Usage: {} {} PEER_ADDR DATA_PORT CONSENSUS_HASH", &argv[0], &argv[1]);
            process::exit(1);
        }
```

File: stackslib/src/net/inv/nakamoto.rs [hunk 8]
```diff
@@ -188,23 +236,45 @@ impl InvGenerator {
...
-            if let Some(ancestor_tip_id) =
-                self.find_ancestor_processed_tenures(chainstate, tip_block_id)?
+            if let Some((ancestor_tip_id, intermediate_tenures)) =
+                self.find_ancestor_processed_tenures(chainstate, &tip_block_id)?
             {
-                let ancestor_tenures = self
+                // The table removals here are for cache maintenance.
+                //
+                // Between successive calls to this function, the Stacks tip (identified by
+                // `tip_block_ch` and `tip_block_bh) can advance as more blocks are discovered.
```
Comment (hstove) [inline stackslib/src/net/inv/nakamoto.rs:254]:
```suggestion
                // `tip_block_ch` and `tip_block_bh`) can advance as more blocks are discovered.
```

**Review by hstove — CHANGES_REQUESTED** [review]
Just some tiny nits, otherwise LGTM!

**Comment by hstove** [comment]
Confirmed that running this on my Nakamoto Testnet node has fixed the issue of not being able to catch all the way back up to the tip

File: stackslib/src/net/api/getsortition.rs [hunk 9]
```diff
@@ -377,3 +377,34 @@ impl HttpResponse for GetSortitionHandler {
...
+    /// Make a new getinfo request to this endpoint
+    pub fn new_get_sortition(
+        host: PeerHost,
+        sort_key: &str,
+        sort_value: &str,
+    ) -> StacksHttpRequest {
+        StacksHttpRequest::new_for_peer(
+            host,
+            "GET".into(),
+            format!("/v3/sortitions/{}/{}", sort_key, sort_value),
```
Comment (kantai) [inline stackslib/src/net/api/getsortition.rs:395]:
```suggestion
            format!("{RPC_SORTITION_INFO_PATH}/{sort_key}/{sort_value}"),
```

File: stackslib/src/net/api/getsortition.rs [hunk 10]
```diff
@@ -377,3 +377,34 @@ impl HttpResponse for GetSortitionHandler {
...
+            HttpRequestContents::new(),
+        )
+        .expect("FATAL: failed to construct request from infallible data")
+    }
+
+    pub fn new_get_sortition_consensus(host: PeerHost, ch: &ConsensusHash) -> StacksHttpRequest {
+        Self::new_get_sortition(host, "consensus", &format!("{}", ch))
```
Comment (kantai) [inline stackslib/src/net/api/getsortition.rs:402]:
```suggestion
        Self::new_get_sortition(host, "consensus", &ch.to_string())
```

**Review by kantai — COMMENTED** [review]
LGTM, just a few comments.

File: stackslib/src/main.rs (hunk 6 above)
Comment (jcnelson) [reply stackslib/src/main.rs:1161]: Yes, this is currently expected.  This PR also fixes this -- nodes accidentally broadcast messages to unauthenticated peers (which causes this).

**Review by hstove — DISMISSED** [review]

File: stackslib/src/net/api/getsortition.rs [hunk 11]
```diff
@@ -381,3 +381,34 @@ impl HttpResponse for GetSortitionHandler {
         Ok(HttpResponsePayload::try_from_json(sortition_info)?)
     }
 }
+
+impl StacksHttpRequest {
+    /// Make a new getinfo request to this endpoint
```
Comment (obycode) [inline stackslib/src/net/api/getsortition.rs:386]: nit:
```suggestion
    /// Make a new request to this endpoint
```

**Review by obycode — APPROVED** [review]
Looks good. Just pointed out a copy pasta in a comment.

**Review by hstove — APPROVED** [review]

**Review by obycode — APPROVED** [review]

**Review by kantai — APPROVED** [review]
