### PR TITLE
Fix/multi miner fixes jude

### LINKED ISSUE #4998: Signers should broadcast block themselves when signing threshold is crossed
Signers should broadcast nakamoto blocks themselves (not needing to wait for the miner to do so) once the signing threshold is crossed.

To do this:

1. Signers need to handle the signer message for block response (they already receive the message, they would just need to store the signatures)
2. On storing signatures, they check if the threshold is crossed, and if so, they broadcast the block (there's already a stacks-client implementation for block push)

I suspect that most of the work here is just in the signerdb for adding and updating signatures in the block info tracking.

### PR DESCRIPTION
**Pull request by jcnelson**
This is a branch I'm maintaining that has fixes to the networking stack and chainstate that I discover from my multiminer setup.

I'll branch PRs from this to `develop` periodically, as needed.

EDIT:  This fixes #4998, #5048, and #5030, and adds test coverage.

EDIT: This also makes the following downstream changes:

* `/v2/block_proposal` is now `/v3/block_proposal`.  This was an oversight from earlier; this code only works in Nakamoto
* `/v2/stacker_set` is now `/v3/stacker_set` for the same reason.
* The `block_proposal_token` connection option has been renamed to `auth_token`, since it gets consumed in `/v3/blocks/upload` now as well as `/v3/block_proposal`.  In the former case, the presence of this token as well as a `?broadcast=1` query directive will force the node to broadcast a block even if it's already present in the chainstate.

### CODE REVIEW

**Comment by obycode** [comment]
cf0a2d4 is being deployed to naka-1 and naka-3

**Comment by jcnelson** [comment]
Look at all those green checks!

File: testnet/stacks-node/src/tests/signer/v0.rs [hunk 1]
```diff
@@ -540,6 +543,9 @@ fn miner_gather_signatures() {
     signer_test.boot_to_epoch_3();
     let timeout = Duration::from_secs(30);
 
+    // give the system a chance to mine a Nakamoto block
+    sleep_ms(30_000);
```
Comment (obycode) [inline testnet/stacks-node/src/tests/signer/v0.rs:547]: Is this sleep unnecessary?

File: testnet/stacks-node/src/tests/signer/v0.rs [hunk 2]
```diff
@@ -1786,6 +1911,9 @@ fn end_of_tenure() {
         .reward_cycle_to_block_height(final_reward_cycle)
         - 2;
 
+    // give the system a chance to mine a Nakamoto block
+    sleep_ms(30_000);
```
Comment (obycode) [inline testnet/stacks-node/src/tests/signer/v0.rs:1915]: Is there anything triggering a block to be produced?

**Review by obycode — COMMENTED** [review]
Looks good. I just have some minor comments.

File: testnet/stacks-node/src/nakamoto_node/peer.rs [hunk 3]
```diff
@@ -190,7 +190,7 @@ impl PeerThread {
             info!("`PeerNetwork::bind()` skipped, already bound");
         }
 
-        let poll_timeout = cmp::min(5000, config.miner.first_attempt_time_ms / 2);
+        let poll_timeout = cmp::min(1000, config.miner.first_attempt_time_ms / 2);
```
Comment (kantai) [inline testnet/stacks-node/src/nakamoto_node/peer.rs:193]: Can this invoke `config.get_poll_time()`?

File: testnet/stacks-node/src/tests/nakamoto_integrations.rs [hunk 4]
```diff
@@ -3895,31 +3914,65 @@ fn forked_tenure_is_ignored() {
         thread::sleep(Duration::from_secs(1));
     }
 
-    info!("Tenure B broadcasted a block. Issue the next bitcon block and unstall block commits.");
-    let block_tenure_b = NakamotoChainState::get_canonical_block_header(chainstate.db(), &sortdb)
+    sleep_ms(1000);
```
Comment (kantai) [inline testnet/stacks-node/src/tests/nakamoto_integrations.rs:3917]: Rather than a bunch of `sleep_ms` invocations, this should `wait_for()` on a mutex or `get_chain_info` result, etc. for exactly the conditions that the `sleep_ms` invocations are attempting to wait for. This will make things more resilient to timing issues across computers, CI, etc, but also make the tests more explicit about the behavior they are waiting on.

File: testnet/stacks-node/src/tests/signer/v0.rs (hunk 1 above)
Comment (kantai) [reply testnet/stacks-node/src/tests/signer/v0.rs:547]: If the sleep is necessary, it should be replaced with a `wait_for()` invocation that checks for the condition the sleep is waiting on here -- I think the `blocks_processed` mutex could be used here (or invoking `get_chain_info`)

File: testnet/stacks-node/src/tests/signer/v0.rs [hunk 5]
```diff
@@ -890,13 +905,17 @@ fn forked_tenure_testing(
...
+            // need)
+            config.broadcast_signed_blocks = false;
         },
         |_| {},
         &[],
     );
     let http_origin = format!("http://{}", &signer_test.running_nodes.conf.node.rpc_bind);
 
     signer_test.boot_to_epoch_3();
+    sleep_ms(1000);
```
Comment (kantai) [inline testnet/stacks-node/src/tests/signer/v0.rs:918]: Same comment as elsewhere, if a sleep is necessary, it should be replaced with `wait_for()` and the condition.

File: testnet/stacks-node/src/tests/signer/v0.rs [hunk 6]
```diff
@@ -2005,10 +2135,105 @@ fn retry_on_timeout() {
...
+    let sender_nonce = 0;
+    let transfer_tx =
+        make_stacks_transfer(&sender_sk, sender_nonce, send_fee, &recipient, send_amt);
+    submit_tx(&http_origin, &transfer_tx);
+
+    debug!("Transaction sent; waiting for block-mining");
+
+    let start = Instant::now();
+    let duration = 60;
+    loop {
```
Comment (kantai) [inline testnet/stacks-node/src/tests/signer/v0.rs:2195]: To cut down on how often this logic was getting repeated in tests, I added `wait_for()`, should use it here.

File: testnet/stacks-node/src/nakamoto_node/relayer.rs [hunk 7]
```diff
@@ -748,7 +809,10 @@ impl RelayerThread {
         )?;
 
         let new_miner_handle = std::thread::Builder::new()
-            .name(format!("miner.{parent_tenure_start}"))
+            .name(format!(
+                "miner.{parent_tenure_start} (bound ({},{})",
+                &self.config.node.p2p_bind, &self.config.node.rpc_bind
```
Comment (kantai) [inline testnet/stacks-node/src/nakamoto_node/relayer.rs:814]: Can this use the port numbers instead of the full bind address? I can't think of a situation where the bind address is differentiating anything more than the bind ports already are, and it substantially reduces the width of the logs.

**Review by kantai — COMMENTED** [review]
This pretty much LGTM, left some comments throughout. At a high level, the tests shouldn't rely on constant-time sleeps and instead they should wait for mutex conditions or similar. Then, the changes in the downloader and network stack should have tests included for the changes.

File: testnet/stacks-node/src/tests/signer/v0.rs (hunk 1 above)
Comment (jcnelson) [reply testnet/stacks-node/src/tests/signer/v0.rs:547]: Yes, it's necessary, and I'll replace it with `wait_for()`.  It's waiting for the Stacks chain tip to advance.

File: testnet/stacks-node/src/tests/signer/v0.rs (hunk 2 above)
Comment (jcnelson) [reply testnet/stacks-node/src/tests/signer/v0.rs:1915]: It's waiting for the Stacks chain tip to advance.  I'll refactor to use `wait_for()`.

File: stackslib/src/chainstate/nakamoto/staging_blocks.rs [hunk 8]
```diff
@@ -325,6 +325,24 @@ impl<'a> NakamotoStagingBlocksConnRef<'a> {
...
+        &self,
+        consensus_hash: &ConsensusHash,
+    ) -> Result<Vec<NakamotoBlock>, ChainstateError> {
+        let qry = "SELECT data FROM nakamoto_staging_blocks WHERE is_tenure_start = 1 AND consensus_hash = ?1";
+        let args = params![consensus_hash];
+        let block_data: Vec<Vec<u8>> = query_rows(self, qry, args)?;
+        Ok(block_data
+            .into_iter()
+            .filter_map(|block_vec| NakamotoBlock::consensus_deserialize(&mut &block_vec[..]).ok())
+            .collect())
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/chainstate/nakamoto/staging_blocks.rs:343]: This is a best-effort function used by the downloader, so I think it's fine to just log the error.  There's nothing else the downloader can do if some blocks fail to load, but it's still possible for the downloader to make forward progress if it gets at least one block.

File: stackslib/src/net/download/nakamoto/tenure_downloader.rs [hunk 9]
```diff
@@ -651,10 +643,9 @@ impl NakamotoTenureDownloader {
         &mut self,
         response: StacksHttpResponse,
     ) -> Result<Option<Vec<NakamotoBlock>>, NetError> {
-        self.idle = true;
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/net/download/nakamoto/tenure_downloader.rs:654]: > Is the change here intended to make it so that self.idle is set to true after this function has successfully run, but not if it errors?

Yes; this had not been the case before this patch.

> Does it matter that the self.idle remains in the "old state" for error conditions?

That's the intent -- the downloader set will re-try the next download step if it can.

I can make that refactoring

File: stacks-signer/src/signerdb.rs [hunk 10]
```diff
@@ -197,19 +229,66 @@ static DROP_SCHEMA_0: &str = "
...
+    signer_signature_hash TEXT NOT NULL,
+    -- signtaure itself
+    signature TEXT NOT NULL,
+    PRIMARY KEY (signature)
+) STRICT;"#;
+
+static CREATE_INDEXES_2: &str = r#"
+CREATE INDEX IF NOT EXISTS block_reward_cycle_and_signature ON block_signatures(signer_signature_hash);
+"#;
+
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:266]: I'm not sure it matters, since the system isn't released yet.  Realistically, we don't need migration logic anywhere in the signer.

File: stacks-signer/src/signerdb.rs [hunk 11]
```diff
@@ -427,6 +524,70 @@ impl SignerDb {
...
+    ) -> Result<Vec<MessageSignature>, DBError> {
+        let qry = "SELECT signature FROM block_signatures WHERE signer_signature_hash = ?1";
+        let args = params![block_sighash];
+        let sigs_txt: Vec<String> = query_rows(&self.db, qry, args)?;
+        let mut sigs = vec![];
+        for sig_txt in sigs_txt.into_iter() {
+            let sig = serde_json::from_str(&sig_txt).map_err(|_| DBError::ParseError)?;
+            sigs.push(sig);
+        }
+        Ok(sigs)
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:561]: I didn't know that you could do that.  Thanks!

File: stackslib/src/net/download/nakamoto/tenure_downloader_set.rs [hunk 12]
```diff
@@ -431,11 +426,11 @@ impl NakamotoTenureDownloaderSet {
...
-        test_debug!("schedule: {:?}", schedule);
-        test_debug!("available: {:?}", &available);
-        test_debug!("tenure_block_ids: {:?}", &tenure_block_ids);
-        test_debug!("inflight: {}", self.inflight());
-        test_debug!(
+        debug!("schedule: {:?}", schedule);
+        debug!("available: {:?}", &available);
+        debug!("tenure_block_ids: {:?}", &tenure_block_ids);
+        debug!("inflight: {}", self.inflight());
+        debug!(
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/net/download/nakamoto/tenure_downloader_set.rs:433]: Sure

File: testnet/stacks-node/src/tests/neon_integrations.rs [hunk 13]
```diff
@@ -694,7 +694,10 @@ pub fn run_until_burnchain_height(
         if !next_result {
             return false;
         }
-        let tip_info = get_chain_info(&conf);
+        let Ok(tip_info) = get_chain_info_result(&conf) else {
+            sleep_ms(1000);
+            continue;
+        };
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply testnet/stacks-node/src/tests/neon_integrations.rs:700]: If we just used `get_chain_info()`, the test can sometimes panic if this code is reached while the node is in the middle of shutting down the neon runloop and starting the nakamoto runloop.  In the absence of a thread panic, `get_chain_info()` can only fail if the connection is refused, and that can only happen during the epoch 2/3 switchover.

File: testnet/stacks-node/src/nakamoto_node/relayer.rs (hunk 7 above)
Comment (jcnelson) [reply testnet/stacks-node/src/nakamoto_node/relayer.rs:814]: Sure; I wasn't even intending to keep this new format anyway

File: stacks-signer/src/v0/signer.rs [hunk 14]
```diff
@@ -53,10 +57,14 @@ pub struct Signer {
     pub signer_addresses: Vec<StacksAddress>,
     /// The reward cycle this signer belongs to
     pub reward_cycle: u64,
+    /// Reward set signer addresses and their weights
+    pub signer_weights: HashMap<StacksAddress, usize>,
```
Comment (hstove) [inline stacks-signer/src/v0/signer.rs:61]: With this change, should we just drop `signer_addresses` and maybe use an `IndexMap` to preserve the order we want?

File: testnet/stacks-node/src/nakamoto_node/miner.rs [hunk 15]
```diff
@@ -644,8 +716,27 @@ impl BlockMinerThread {
...
+            let throw: u8 = thread_rng().gen_range(0..100);
+            throw < drop_prob
+        } else {
+            false
+        };
+
+        if will_drop {
+            info!("Fault injection: drop block {}", &block_id);
+            return Ok(());
+        }
```
[the remark this answers is not in the document]
Comment (hstove) [reply testnet/stacks-node/src/nakamoto_node/miner.rs:737]: Is this code intended only for testing usecases? If only for testing, can we add a `#[cfg(test)]` branch?

File: testnet/stacks-node/src/nakamoto_node/relayer.rs [hunk 16]
```diff
@@ -375,22 +375,84 @@ impl RelayerThread {
...
+                SortitionDB::get_block_snapshot_consensus(sortdb.conn(), &cur_stacks_tip_ch)
+                    .expect("FATAL: failed to query sortiiton DB for epoch")
+                    .expect("FATAL: no sortition for canonical stacks tip");
+
+            let cur_epoch =
+                SortitionDB::get_stacks_epoch(sortdb.conn(), stacks_tip_sn.block_height)
+                    .expect("FATAL: failed to query sortition DB for epoch")
+                    .expect("FATAL: no epoch defined for existing sortition");
+
+            if cur_epoch.epoch_id != StacksEpochId::Epoch30 {
```
Comment (hstove) [inline testnet/stacks-node/src/nakamoto_node/relayer.rs:418]: Apologies if I'm mistaken here!
```suggestion
            if cur_epoch.epoch_id < StacksEpochId::Epoch30 {
```

File: testnet/stacks-node/src/config.rs [hunk 17]
```diff
@@ -2652,6 +2671,14 @@ impl NodeConfigFile {
...
                 .filter_map(|contract_id| QualifiedContractIdentifier::parse(contract_id).ok())
                 .collect(),
+            fault_injection_block_push_fail_probability: if self
+                .fault_injection_block_push_fail_probability
+                .is_some()
+            {
+                self.fault_injection_block_push_fail_probability
+            } else {
+                default_node_config.fault_injection_block_push_fail_probability
+            },
```
Comment (hstove) [inline testnet/stacks-node/src/config.rs:2681]: Also related to my other comment around using this: if this is field is for tests, do we even need to have it in `NodeConfigFile`?

File: testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs [hunk 18]
```diff
@@ -719,8 +754,29 @@ impl SignCoordinator {
                 }
             };
 
+            // look in the nakamoto staging db -- a block can only get stored there if it has
+            // enough signing weight to clear the threshold
+            if let Ok(Some((stored_block, _sz))) = chain_state
```
Comment (hstove) [inline testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs:759]: I feel like the order of operations here is maybe wrong - basically it's currently:

- wait up to 500ms for a StackerDB event
- If we get a timeout, start over and wait another 500ms
- only if we got an event, then we check our chainstate for a Nakamoto block

Perhaps we should check our chainstate first, and then poll for a StackerDB event?

File: testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs [hunk 19]
```diff
@@ -758,8 +814,41 @@ impl SignCoordinator {
...
+                                    total_reject_weight,
+                                    self.total_weight,
+                                    &block.header.consensus_hash,
+                                    &block.header.block_hash()
+                                );
+                                counters.bump_naka_rejected_blocks();
+                                return Err(NakamotoNodeError::SignersRejected);
+                            }
+                        } else {
+                            debug!("Received rejected block response for a block besides my own. Ignoring.");
```
Comment (hstove) [inline testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs:850]: Very nit but I prefer an early return/continue, just because it's a bit easier to read:

```rust
if rejected_data.signer_signature_hash != block.header.signer_signature_hash() {
    debug!("Received rejected block response for a block besides my own. Ignoring.");
    continue;
}
```

**Review by hstove — CHANGES_REQUESTED** [review]
Great stuff! Just a few small notes on potential changes

File: stacks-signer/src/config.rs [hunk 20]
```diff
@@ -201,6 +203,8 @@ pub struct GlobalConfig {
     pub first_proposal_burn_block_timing: Duration,
     /// How much time to wait for a miner to propose a block following a sortition
     pub block_proposal_timeout: Duration,
+    /// Broadcast a block to the node if we gather enough signatures from other signers
+    pub broadcast_signed_blocks: bool,
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/config.rs:207]: This field is used to inject faults into the broadcast logic.  The integration test framework sets it to `false`.

File: stacks-signer/src/signerdb.rs [hunk 21]
```diff
@@ -197,19 +229,66 @@ static DROP_SCHEMA_0: &str = "
...
+   DROP TABLE IF EXISTS db_config;";
+
+static CREATE_BLOCKS_TABLE_2: &str = "
+CREATE TABLE IF NOT EXISTS blocks (
+    reward_cycle INTEGER NOT NULL,
+    signer_signature_hash TEXT NOT NULL,
+    block_info TEXT NOT NULL,
+    consensus_hash TEXT NOT NULL,
+    signed_over INTEGER NOT NULL,
+    broadcasted INTEGER NOT NULL,
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:245]: Sqlite doesn't have a `bool` storage class -- `bool` is just a synonym for `integer`.

[the remark this answers is not in the document]
Comment (hstove) [reply stacks-signer/src/signerdb.rs:245]: Ah, gotcha! I see the line `is_tenure_start BOOL NOT NULL` in `nakamoto_staging_blocks`, that must basically alias an integer column?

[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:245]: Yup, same thing.

I was in a hurry when I wrote the above, but it was intended as a question.  While there's nothing to be gained by treating it as a `bool` in the schema definition (besides conveying intent), I think it's entirely reasonable to treat `broadcasted` as a timestamp as well.  Is that something you'd be interested in?

File: stacks-signer/src/signerdb.rs [hunk 22]
```diff
@@ -197,19 +229,66 @@ static DROP_SCHEMA_0: &str = "
...
+    -- the sighash is sufficient to uniquely identify the block across all burnchain, PoX,
+    -- and stacks forks.
+    signer_signature_hash TEXT NOT NULL,
+    -- signtaure itself
+    signature TEXT NOT NULL,
+    PRIMARY KEY (signature)
+) STRICT;"#;
+
+static CREATE_INDEXES_2: &str = r#"
+CREATE INDEX IF NOT EXISTS block_reward_cycle_and_signature ON block_signatures(signer_signature_hash);
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:264]: Sure; will change

File: stacks-signer/src/signerdb.rs [hunk 23]
```diff
@@ -403,14 +498,16 @@ impl SignerDb {
             "sighash" => %hash,
             "block_id" => %block_id,
             "signed" => %signed_over,
+            "broadcasted" => %broadcasted,
             "vote" => vote
         );
         self.db
             .execute(
-                "INSERT OR REPLACE INTO blocks (reward_cycle, burn_block_height, signer_signature_hash, block_info, signed_over, stacks_height, consensus_hash) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
+                "INSERT OR REPLACE INTO blocks (reward_cycle, burn_block_height, signer_signature_hash, block_info, signed_over, broadcasted, stacks_height, consensus_hash) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stacks-signer/src/signerdb.rs:506]: Great catch! will fix

File: stacks-signer/src/v0/signer.rs (hunk 14 above)
Comment (jcnelson) [reply stacks-signer/src/v0/signer.rs:61]: So, the reason I'm using `.find` is because we only want to check the address bytes, not the address version.  This removes a category of bugs that could arise from needing to preserve access to the `.mainnet` bool pervasively in the code.  In order for the above code to work, we'd need to construct the `StacksAddress` with `.mainnet` instead of `true`, and that begets the question of where can it find `.mainnet`.  But we don't need to answer that question to solve the problem at hand.

Comment (jcnelson) [reply stacks-signer/src/v0/signer.rs:61]: Also, `IndexMap` isn't in the rust standard library.

File: testnet/stacks-node/src/config.rs (hunk 17 above)
Comment (jcnelson) [reply testnet/stacks-node/src/config.rs:2681]: It's used not only for tests, but also for multi-miner testing.  So, it needs to be in the config file.

File: testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs (hunk 18 above)
Comment (jcnelson) [reply testnet/stacks-node/src/nakamoto_node/sign_coordinator.rs:759]: Yup, you're right

File: stacks-signer/src/signerdb.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (kantai) [reply stacks-signer/src/signerdb.rs:266]: Yeah, I don't think it matters whether there's a DROP or ALTER. There does need to be some logic around this, though, because signers running in mock signing mode may want to upgrade a version without having to manually clear their data directories.

The only point I'd make is that it would be good to have some hygiene here so that we don't end up just having 3 copy-pasted schemas (maybe change the prior schemas to just be empty as long as the DROPs are being executed anyways?)

File: stackslib/src/net/chat.rs [hunk 24]
```diff
@@ -1999,9 +1984,29 @@ impl ConversationP2P {
         ) {
             Ok(Some(chunk)) => chunk,
             Ok(None) => {
-                // request for a stale chunk
+                // TODO: this is racey
```
Comment (jferrant) [inline stackslib/src/net/chat.rs:1987]: Do we have a ticket to address the raceyness or is it gonna get gixed in this PR?

Comment (jcnelson) [reply stackslib/src/net/chat.rs:1987]: It's #5067

File: stacks-signer/src/v0/signer.rs (hunk 14 above)
Comment (hstove) [reply stacks-signer/src/v0/signer.rs:62]: Gotcha, makes sense!

**Review by hstove — DISMISSED** [review]

**Review by obycode — APPROVED** [review]
lgtm!

**Comment by jferrant** [comment]
Only thing I didn't like is the use of sleep in tests which Aaron has already pointed out! LGTM

**Review by jferrant — DISMISSED** [review]

**Review by obycode — APPROVED** [review]

**Comment by jcnelson** [comment]
@hstove @jferrant need one of you to re-approve please :pray: all tests are passing now

**Review by hstove — APPROVED** [review]

**Review by hstove — APPROVED** [review]

**Review by jferrant — APPROVED** [review]
