### PR TITLE
Fix: `from-consensus-buff?`

### LINKED ISSUE #6683: Runtime error when doing `from-consensus-buff?` with an empty buffer
When calling `from-consensus-buff?` with an empty buffer, you get the runtime error:

```
Unchecked(CostComputationFailed("Error evaluating result of cost function ST000000000000000000002AMW42H.costs-3.cost_from_consensus_buff: Arithmetic(\"log2 must be passed a positive integer\")\n Stack Trace: \n"))
```

This is present in both epoch 3.2 and 3.3.

Example replication: `(from-consensus-buff? bool 0x)`

The expected behavior is that this function returns `none`, which is the normal return when deserialization fails.

### PR DESCRIPTION
**Pull request by brice-stacks**
### Description

This fixes the runtime error that is hit when evaluating `from-consensus-buff?` with an empty buffer. This should return `none`, but currently, it will hit a runtime error due to the cost computation passing a `0` into a call to `log2`.

It builds on top of #6802, so I will leave it in draft until that one is merged.

### Applicable issues

- fixes #6683

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo

### CODE REVIEW

File: stackslib/src/chainstate/tests/runtime_analysis_tests.rs [hunk 1]
```diff
@@ -1323,6 +1327,22 @@ fn invalid_characters_detected_invalid_utf8() {
...
+        exclude_clarity_versions: &[ClarityVersion::Clarity1], // Clarity1 does not support from-consensus-buff?
+    );
+}
+
+/// Error (pre Clarity 5): [`CostErrors::CostComputationFailed`]
+/// Caused by: passing an empty buffer to `from-consensus-buff?`
+/// Outcome: block accepted.
+/// After Clarity 5: Contract call executes successfully and returns `(ok none)`
+#[test]
+fn empty_consensus_buff() {
```
Comment (federico-stacks) [inline stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: it seems we already have 2 tests about this in `runtime_tests.rs`, currently failing due snapshot update:
- `arithmetic_zero_n_log_n_cdeploy`
- `arithmetic_zero_n_log_n_ccall`

maybe, we could just update them (snapshot and documentation) instead of adding the new test?

Comment (federico-stacks) [reply stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: and probably we could consider to move those 2 tests into `runtime_analysis_tests.rs`. Actually they produce a `RuntimeCheckErrorKind::CostComputationFailed` (as also reported in the related test description)

Comment (brice-stacks) [reply stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: You're right, that makes sense. Thanks!

Comment (brice-stacks) [reply stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: Done in [a8aae83](https://github.com/stacks-network/stacks-core/pull/6820/commits/a8aae83bf8eb7e1a9cad4a564675d55d96d28917)

**Comment by benjamin-stacks** [comment]
Functionally this does what it says on the tin, so I'm approving it.

However, I want to leave a few notes from a reader who's new to this code.

First, the method `protects_logn_cost_fn` feels like it's trying to be generic while in fact only handling one specific case. From Clarity 5 on, it's not like *any* call to `logn` is always going to be protected -- it's just the particular call from `cost_from_consensus_buff`, and it's not even about `logn` but `nlogn` (which are independently implemented).

A new or changed cost function in the future might as well call `nlogn` and *not* be protected.

In addition, it's not obvious why in `from_consensus_buff` the `input` is capped at `1`, since the fact that its cost is *O(n&nbsp;log&nbsp;n)* is just an implementation detail of the cost function. A future change to `cost_from_consensus_buff` that does not have that cost curve would make this capping potentially invalid.

And finally, *x log x* has a removable discontinuity at 0 -- it tends to 0 as x tends to 0. So you could make the argument that `nlogn(0, a, b) == b` is a valid result.

Based on all that, my suggestion would be the following:

- Rename the method to `protects_nlogn_cost_fn` (or `nlogn_cost_fn_handles_zero` or something more specific like `from_concesus_buff_handles_empty_buffer`)
- Change the implementation of `nlogn` to explicitly return `b` if `n == 0`, and never fail.
- Reverse the logic in `from_consensus_buff` to return the expected error directly if the buffer is empty and the Clarity version is below 5, with an explanatory comment on the backwards compatibility.

That way, future uses of `nlogn` are universally protected,  while still having the backwards-compatibility code truly isolated.

**Comment by brice-stacks** [comment]
Thanks for that detailed review Ben 🙌. I agree with you that the `protects_nlogn_cost_fn` is a bit weird... initially, I thought there were other cases where this could happen, but then I didn't find any. I don't think I'd like to change the `nlogn` implementation, at least not in this PR, since it would require a new costs contract, but we should consider that for the next cost contract update.

Current implementation for `logn` and `nlogn`:
```clarity
;; LogN cost-assessment function
(define-private (logn (n uint) (a uint) (b uint))
    (+ (* a (log2 n)) b))

;; NLogN cost-assessment function
(define-private (nlogn (n uint) (a uint) (b uint))
    (+ (* a (* n (log2 n))) b))
```

**Comment by benjamin-stacks** [comment]
> since it would require a new costs contract

Ah I didn't know there was also a Clarity implementation of the cost functions.

But -- don't you have to update those anyway since this no longer matches the VM's implementation?

```
(define-read-only (cost_from_consensus_buff (n uint))
    (runtime (nlogn n u3 u185)))
```

**Comment by brice-stacks** [comment]
> But -- don't you have to update those anyway since this no longer matches the VM's implementation?

No, we're just changing `n`.

**Comment by benjamin-stacks** [comment]
> No, we're just changing `n`.

Right, but it fails when you pass a 0, while the VM version now works when you pass an empty buffer, so why is this discrepancy okay?

(I totally trust your decision on all this -- I'm just trying to understand *how* we decide such things.)

File: stackslib/src/chainstate/tests/runtime_analysis_tests.rs [hunk 2]
```diff
@@ -20,6 +20,8 @@ use std::collections::HashMap;
 use clarity::types::StacksEpochId;
 #[allow(unused_imports)]
 use clarity::vm::analysis::RuntimeCheckErrorKind;
+#[allow(unused_imports)]
+use clarity::vm::costs::CostErrors;
```
Comment (federico-stacks) [inline stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: nit: this import can be removed

File: stackslib/src/chainstate/tests/runtime_analysis_tests.rs (hunk 1 above)
Comment (federico-stacks) [reply stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: What do you think about the comment above about moving the 2 tests to `runtime_analysis_tests.rs`? 

I would be ok even leave them in the `runtime_tests.rs`, but could be useful to fix the documentation in `runtime_analysis_tests.rs` where we have the variant registered like this: `CostComputationFailed(_) => Unreachable_ExpectLike`.  We could:
- make the 2 test `pub`, and
- attach them to the `CostComputationFailed` as `Tested(...)`

Comment (brice-stacks) [reply stackslib/src/chainstate/tests/runtime_analysis_tests.rs]: Ah, sorry I missed that comment earlier. I went ahead and moved them into runtime_analysis_tests.rs. 04f6a8e9e57fe4874f34dd16267b2a2fa5347472

**Comment by brice-stacks** [comment]
> Right, but it fails when you pass a 0, while the VM version now works when you pass an empty buffer, so why is this discrepancy okay?

We can make this change using the existing costs contract. It does change the cost for some transactions, which is why it is gated by Clarity version. No existing contracts can run Clarity 5, so it is okay to change the cost of Clarity 5 contracts only.

> (I totally trust your decision on all this -- I'm just trying to understand how we decide such things.)

Don't trust, verify. Keep the good questions coming and I'll try to answer them as best I can.

**Review by federico-stacks — APPROVED** [review]

**Comment by benjamin-stacks** [comment]
> No existing contracts can run Clarity 5, so it is okay to change the cost of Clarity 5 contracts only.

Ah yes, that makes sense now. Thank you for the explanation!

**Review by benjamin-stacks — APPROVED** [review]
