### PR TITLE
feat: add `--postcondition-mode` option to `blockstack-cli publish` + anchor mode bug fix

### LINKED ISSUE #6194: Add flag to override postcondition mode in blockstack-cli publish
Currently defaults to `Deny` mode:

- https://github.com/stacks-network/stacks-core/blob/7d8b675daecce4034c348a9d5b3c6563cdb06005/stackslib/src/chainstate/stacks/transaction.rs#L742
- https://github.com/stacks-network/stacks-core/blob/7d8b675daecce4034c348a9d5b3c6563cdb06005/stackslib/src/blockstack_cli.rs#L312

Would be useful to support an explicit `--postcondition-mode` flag to allow switching to `Allow`, keeping `Deny` as default.

### PR DESCRIPTION
**Pull request by fdefelici**
### Description

This change, add `--postcondition-mode [allow, deny]` option to `blockstack-cli publish` command.

Default mode is `deny`, preserving behaviour before this patch.

It can be used like this:

```
blockstack-cli contract-call \
    ... \
    --postcondition-mode allow
```
### Applicable issues

- fixes #6194 

### Additional info (benefits, drawbacks, caveats)

To be noted that this change fix a bug that prevented the chance of using the anchor mode options. This was due to argument lenght check to be equals to the number of the mandatory parameters (5).

https://github.com/stacks-network/stacks-core/blob/7d8b675daecce4034c348a9d5b3c6563cdb06005/stackslib/src/blockstack_cli.rs#L380-L391

Specific unit tests has been added to confirm that anchor mode options are now working properly.

### Checklist

- [x] Test coverage for new or modified code paths
- [x] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

File: stackslib/src/blockstack_cli.rs [hunk 1]
```diff
@@ -340,15 +344,21 @@ fn parse_anchor_mode(
     for i in 0..num_args {
         if args[i] == "--microblock-only" {
             if idx > 0 {
-                return Err(CliError::Message(format!("USAGE:\n {}", usage,)));
+                return Err(CliError::Message(format!(
+                    "Multiple anchor mode detected.\n\nUSAGE:\n{}",
```
Comment (moodmosaic) [inline stackslib/src/blockstack_cli.rs]:
```suggestion
                    "Multiple anchor modes detected.\n\nUSAGE:\n{}",
```

File: stackslib/src/blockstack_cli.rs [hunk 2]
```diff
@@ -340,15 +344,21 @@ fn parse_anchor_mode(
...
             }
 
             offchain_only = true;
             idx = i;
         }
         if args[i] == "--block-only" {
             if idx > 0 {
-                return Err(CliError::Message(format!("USAGE:\n {}", usage,)));
+                return Err(CliError::Message(format!(
+                    "Multiple anchor mode detected.\n\nUSAGE:\n{}",
```
Comment (moodmosaic) [inline stackslib/src/blockstack_cli.rs]:
```suggestion
                    "Multiple anchor modes detected.\n\nUSAGE:\n{}",
```

File: stackslib/src/blockstack_cli.rs [hunk 3]
```diff
@@ -375,15 +428,16 @@ fn handle_contract_publish(
     let mut args = args_slice.to_vec();
 
     if !args.is_empty() && args[0] == "-h" {
-        return Err(CliError::Message(format!("USAGE:\n {}", PUBLISH_USAGE)));
+        return Err(CliError::Message(format!("USAGE:\n{}", PUBLISH_USAGE)));
     }
-    if args.len() != 5 {
+    if args.len() < 5 {
```
Comment (moodmosaic) [inline stackslib/src/blockstack_cli.rs:531]: This is a good catch! I think this explains why anchor mode options were broken - they were being added to the args, making the length > 5, which triggered the error.

File: stackslib/src/blockstack_cli.rs [hunk 4]
```diff
@@ -367,6 +377,49 @@ fn parse_anchor_mode(
     }
 }
 
+fn parse_postcondition_mode(
```
Comment (moodmosaic) [inline stackslib/src/blockstack_cli.rs:486]: I don't think this is a blocker for this PR, but we could perhaps define and reuse some helpers across this function and the `parse_anchor_mode` one, e.g.:
- count_flag_occurrences
- remove_boolean_flag (for anchor mode)
- remove_flag_with_value (for postcondition mode)

as an attempt at separating boolean flags (anchor mode) from value flags (postcondition mode) with helpers, while sharing the common counting logic.

**Review by moodmosaic — DISMISSED** [review]
LGTM! Left some comments but they shouldn't necessarily block merging.

Also tested by publishing this contract, which fails in `deny` mode but works with `--postcondition-mode allow`:

```clar
(let (
  (transfer-0 (stx-transfer? u1000000000 tx-sender 'ST2RSMB4E6X08DZ1HP97GFESXZ2JHD9ZQ3CJ0RCDN))
  (transfer-1 (stx-transfer? u2000000000 tx-sender 'ST38YA3G8F7F7V2C7VW64W25M2GPDRY5NJMSCHG1N))
  (transfer-2 (stx-transfer? u3000000000 tx-sender 'ST3MNJ5Y9RFTDSWNS1CYAB7WS4RYA4EYFTRVAKSXF))
  (transfer-3 (stx-transfer? u4000000000 tx-sender 'ST14QP31JATXRC1GRDE9QTMNW96T9PNHWPKHPH747))
) (ok true))
```

Good fix for both the new feature and the anchor mode bug.

File: stackslib/src/blockstack_cli.rs (hunk 1 above)
Comment (fdefelici) [reply stackslib/src/blockstack_cli.rs]: fixed here: 48c57f5bcc51bf440a48cd2a2990b6a54d3b2b26

File: stackslib/src/blockstack_cli.rs (hunk 2 above)
Comment (fdefelici) [reply stackslib/src/blockstack_cli.rs]: fixed here: 48c57f5bcc51bf440a48cd2a2990b6a54d3b2b26

File: stackslib/src/blockstack_cli.rs (hunk 4 above)
Comment (fdefelici) [reply stackslib/src/blockstack_cli.rs:486]: improved here: 75475241c024359164e1c329ea68cc6ca5e8f269

File: CHANGELOG.md [hunk 5]
```diff
@@ -11,10 +11,16 @@ and this project adheres to the versioning scheme outlined in the [README.md](RE
 
 - Added a new RPC endpoint `/v3/health` to query the node's health status. The endpoint returns a 200 status code with relevant synchronization information (including the node's current Stacks tip height, the maximum Stacks tip height among its neighbors, and the difference between these two). A user can use the `difference_from_max_peer` value to decide what is a good threshold for them before considering the node out of sync. The endpoint returns a 500 status code if the query cannot retrieve viable data.
 
+- Added a new option `--postcondition-mode [allow, deny]` to `blockstack-cli publish` command, to allow/deny post-conditions on the smart contract (default is deny)
```
Comment (obycode) [inline CHANGELOG.md]: The mode doesn't exactly allow/deny post-conditions. It might be better to say "to set the post-condition mode to allow or deny (default is deny)".

File: stackslib/src/blockstack_cli.rs [hunk 6]
```diff
@@ -90,6 +90,10 @@ is that the miner chooses, but you can decide which with the following options:
 
   --microblock-only  indicates to mine this transaction only in a microblock
   --block-only       indicates to mine this transaction only in a block
+
+The use of post-conditions in the contract can be controlled with the following option:
```
Comment (obycode) [inline stackslib/src/blockstack_cli.rs]:
```suggestion
The post-condition mode for the transaction can be controlled with the following option:
```

**Review by obycode — COMMENTED** [review]
Looks good, I just had two minor documentation comments.

File: CHANGELOG.md (hunk 5 above)
Comment (fdefelici) [reply CHANGELOG.md]: fixed here: 4641782e1fa54e52eed910c3b973a0c0fed1bd0c

File: stackslib/src/blockstack_cli.rs (hunk 6 above)
Comment (fdefelici) [reply stackslib/src/blockstack_cli.rs]: fixed here: c286f9a5216f9fafee29d4802e2c91aab99da62d

**Review by obycode — APPROVED** [review]
Lgtm

File: stackslib/src/blockstack_cli.rs (hunk 4 above)
Comment (Jiloc) [reply stackslib/src/blockstack_cli.rs:486]: Not for this PR, but just saying, it would be so nice to use something like https://github.com/clap-rs/clap instead of having to write/review/validate cli parsing logic every time!

Comment (fdefelici) [reply stackslib/src/blockstack_cli.rs:486]: Conversation around this topic is here: https://github.com/stacks-network/stacks-core/issues/4045
