### PR TITLE
Fix/5205

### LINKED ISSUE #5205: [Network] Only one state-machine pass per top-level `PeerNetwork::run()`
Due to the way that the function `PeerNetwork::do_network_work_nakamoto()` is structured, we are inadvertently doing multiple inventory and downloader passes per call to `PeerNetwork::run()`.  This amplifies any I/O-induced slowness and can lead to high latency for StackerDB, NeighborWalk, and HTTP state machines.

### PR DESCRIPTION
**Pull request by jcnelson**
Fixes #5205 so that Nakamoto network state machines run at most once per call to `PeerNetwork::run()`

### CODE REVIEW

**Review by obycode — DISMISSED** [review]
LGTM!

**Review by kantai — COMMENTED** [review]
This LGTM, but is it feasible to add a test for this behavior?

**Comment by jcnelson** [comment]
> This LGTM, but is it feasible to add a test for this behavior?

Arguably, the entire unit / integration test battery is the test.  If this code failed to run the requisite state machines correctly, we'd see widespread failures.

**Review by jferrant — DISMISSED** [review]

**Comment by jcnelson** [comment]
`nakamoto_integrations::clarity_burn_tests` is failing, which is very unexpected

**Comment by jcnelson** [comment]
`nakamoto_integrations::clarity_burn_state` passed locally for me.  Probably a timing issue that got introduced by speeding up the p2p main loop.

File: testnet/stacks-node/src/tests/nakamoto_integrations.rs [hunk 1]
```diff
@@ -5185,51 +5185,21 @@ fn clarity_burn_state() {
...
-
-                    info!("Contract call result: {}", result);
-                    result.clone().expect_result_ok().expect("Ok result");
-                }
-                _ => {
-                    info!("Unsuccessful event: {:?}", event);
-                    panic!("Expected a successful transaction");
-                }
-            });
-
```
Comment (obycode) [inline testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: Is this just deleting the thing the test is supposed to be testing?

Comment (jferrant) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: Yes because it is impossible to test it. They are assuming that the stacks block will be processed AFTER the burn block. Whihc is impossible to ensure. And it already tests interim blocks after which test the same thing which it was TRYING to assert which is that the stacks blocks mined AFTER the burn block are as expected.

Comment (obycode) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: Ah ok, I see. But the thing that we are not testing still then is when the transaction is in the tenure change block. That's important to test because it was buggy in the early implementation. Maybe we can use the fault injection locks that we've put in to force that scenario?

Comment (jferrant) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: I don't understand what you mea. it still does the get_mined_nakamoto_blocks for all mined nakamoto blocks. which will test the same thing as it did before. just won't test it prematurely.

Comment (jferrant) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: I don't think it ever tested the tenure change block...?

Comment (obycode) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: I think we're guaranteeing that the call to `bar` will never be in the first block of a tenure with this change.

Comment (obycode) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: That's what this deleted code was trying to do, but it would be flaky.

Comment (jferrant) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: Ah you want next_block_and_commit rather than new_stacks_block being called as well. Can make that change pretty easily. Not sure it guarantees what you are asking though.

Comment (obycode) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: To ensure we can test that, I think we need to:
1. Pause block production
2. Submit the call to `bar`
3. Mine a bitcoin block
4. Resume block production

Comment (obycode) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: Maybe you could do it with a long `min_time_between_blocks_ms`?

Comment (jferrant) [reply testnet/stacks-node/src/tests/nakamoto_integrations.rs:5232]: EDIT: OHHHH next_block_and_mine_commit will force a stacks block to be mined. Okay one sec.

**Review by obycode — APPROVED** [review]
Awesome. Thanks for fixing that @jferrant!

**Review by hstove — APPROVED** [review]

**Comment by wileyj** [comment]
results of the CI failing test (fyi, the cache has been evicted so a full re-run would be required here).

## tests::nakamoto_integrations::multiple_miners)
passes 

## tests::signer::v0::partial_tenure_fork
```
RUST_BACKTRACE=full BITCOIND_TEST=1 cargo nextest run \
  --no-capture \
  --verbose \
  --tests \
  --workspace \
  --bin stacks-node \
  --run-ignored all \
  --retries 0  \
  --no-fail-fast \
  -E "test(=tests::signer::v0::partial_tenure_fork)"
...
INFO [1726789407.915984] [stackslib/src/net/p2p.rs:4840] [relayer-http://127.0.0.1:51026] Transaction rejected from mempool, {"error":"transaction rejected","reason":"TooMuchChaining","reason_data":{"actual":34,"expected":27,"is_origin":true,"message":"Nonce would exceed chaining limit in mempool","principal":"ST158X7SZWJVG8KET06C64FSRXD0V1ZT31T72SAR5"},"txid":"2aed82542ae19f3509082950d87990e04dd16838465bc0579da97fd94c968832"}
INFO [1726789407.946710] [stackslib/src/net/rpc.rs:556] [p2p-(127.0.0.1:51023,127.0.0.1:51024)] Handled StacksHTTPRequest, verb: POST, path: /v2/mempool/query?page_id=f2cf05a7cb5725983f36cbfa24dbc82566698aa6dacbdf8b658b706c6c4c28fd, processing_time_ms: 0, latency_ms: 0, conn_id: 685, peer_addr: 127.0.0.1:59792, p2p_msg: None
ERRO [1726789410.844647] [testnet/stacks-node/src/tests/nakamoto_integrations.rs:638] [tests::signer::v0::partial_tenure_fork] Timed out waiting for check to process
ERRO [1726789410.844719] [testnet/stacks-node/src/tests/signer/v0.rs:3819] [tests::signer::v0::partial_tenure_fork] Next tenure failed to tick, fork_initiated?: true, miner_1_tenures: 2, miner_2_tenures: 6, min_miner_1_tenures: 1, min_miner_2_tenures: 1, proposed_before_1: 19, proposed_before_2: 35, mined_before_1: 19, mined_before_2: 0, mined_1: 19, mined_2: 0, proposed_1: 19, proposed_2: 35
thread 'tests::signer::v0::partial_tenure_fork' panicked at testnet/stacks-node/src/tests/signer/v0.rs:3835:25:
explicit panic
```

## tests::signer::v0::retry_on_rejection
ran for over 10 minutes, same scrolling WARN
```
RUST_BACKTRACE=full BITCOIND_TEST=1 cargo nextest run \
  --no-capture \
  --verbose \
  --tests \
  --workspace \
  --bin stacks-node \
  --run-ignored all \
  --retries 0  \
  --no-fail-fast \
  -E "test(=tests::signer::v0::retry_on_rejection)"
...
WARN [1726789900.947496] [stacks-signer/src/v0/signer.rs:201] [signer_runloop:3002] Cycle #11 Signer #1: Failed to push block to stacks node: Backoff retry timeout occurred. Stacks node may be down.. Retrying...

```
## tests::signer::v0::empty_sortition

```
RUST_BACKTRACE=full BITCOIND_TEST=1 cargo nextest run \
  --no-capture \
  --verbose \
  --tests \
  --workspace \
  --bin stacks-node \
  --run-ignored all \
  --retries 0  \
  --no-fail-fast \
  -E "test(=tests::signer::v0::empty_sortition)"
  ...
INFO [1726790353.644569] [stackslib/src/net/rpc.rs:556] [p2p-(127.0.0.1:46863,127.0.0.1:65534)] Handled StacksHTTPRequest, verb: GET, path: /v2/info, processing_time_ms: 0, latency_ms: 0, conn_id: 645, peer_addr: 127.0.0.1:38172, p2p_msg: None
ERRO [1726790353.645066] [testnet/stacks-node/src/tests/nakamoto_integrations.rs:623] [tests::signer::v0::empty_sortition] Timed out waiting for block to process, trying to continue test
thread 'tests::signer::v0::empty_sortition' panicked at testnet/stacks-node/src/tests/signer/v0.rs:282:10:
called `Result::unwrap()` on an `Err` value: "Timed out"
stack backtrace:

```

**Comment by obycode** [comment]
`partial_tenure_fork` flakiness is fixed in #5197.
