### PR TITLE
Fix/4793

### LINKED ISSUE #4813: [Chainstate] SelectedAndUnknown-status preprocessed reward set is stored but never updated
The node will preprocess and store a reward cycle before it knows the anchor block, and in doing so, will store a `SelectedAndUnknown`-status reward set to the sortition DB.  This in turn will break a Nakamoto node's ability to load the signing set when it validates a block in the subsequent reward cycle.

The fix is to check and update the sortition DB if the anchor block state transitions from `SelectedAndUnknown` to `SelectedAndKnown`.

### PR DESCRIPTION
**Pull request by jcnelson**
This PR updates the Nakamoto chainstate and networking stack to use the reward cycle's signers instead of the aggregate public key to authenticate Nakamoto blocks (#4793).  In order to do this, this PR also fixes #4813.

Note that the fix for #4813 does _not_ need a schema migration for nodes today which have erroneously stored a `SelectedAndUnknown` reward set, because the impact of doing so is nonexistent.  This would only have required a schema migration if the last reward 2.5 cycle was erroneously set to `SelectedAndUnknown`.

### CODE REVIEW

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 1]
```diff
@@ -4559,12 +4678,14 @@ impl SortitionDB {
         Ok(ret)
     }
 
+    /// DO NOT CALL FROM CONSENSUS CODE
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:4681]: Why shouldn’t this function be invoked by consensus code? What do you mean by consensus code here?

Comment (jcnelson) [reply stackslib/src/chainstate/burn/db/sortdb.rs:4681]: Specifically, because it calls `SortitionDB::get_canonical_sortition_tip()`, which can change whenever a new burnchain block is processed.  If this gets called from block-processing code in any places besides the burnchain block processor in the coordinator, then it's possible that different nodes will get different sortition IDs corresponding to different burnchain blocks while processing the same Stacks block.  That, in turn, can lead to a chain split.

Comment (kantai) [reply stackslib/src/chainstate/burn/db/sortdb.rs:4681]: I see — can you make this comment more specific here, then?

```suggestion
    /// DO NOT call during Stacks block processing (including during Clarity VM evaluation). This function returns the latest data known to the node, which may not have been at the time of original block assembly.
```

Comment (kantai) [reply stackslib/src/chainstate/burn/db/sortdb.rs:4681]: (I think the same comment applies to the rest of the DO NOT CALL comments)

File: stackslib/src/chainstate/coordinator/mod.rs [hunk 2]
```diff
@@ -845,9 +845,21 @@ pub fn get_reward_cycle_info<U: RewardSetProvider>(
...
+        let preprocessed_reward_set =
+            SortitionDB::get_preprocessed_reward_set(&mut tx, &first_prepare_sn.sortition_id)?;
+        let need_to_store = if let Some(reward_cycle_info) = preprocessed_reward_set {
+            // overwrite if we have an unknown anchor block
+            !reward_cycle_info.is_reward_info_known()
+        } else {
+            true
+        };
+        if need_to_store {
+            test_debug!(
```
Comment (kantai) [inline stackslib/src/chainstate/coordinator/mod.rs:857]: Should be debug instead of test_debug and use the KV syntax.

File: stackslib/src/chainstate/coordinator/mod.rs [hunk 3]
```diff
@@ -845,9 +845,21 @@ pub fn get_reward_cycle_info<U: RewardSetProvider>(
                 .expect("FATAL: no start-of-prepare-phase sortition");
 
         let mut tx = sort_db.tx_begin()?;
-        if SortitionDB::get_preprocessed_reward_set(&mut tx, &first_prepare_sn.sortition_id)?
-            .is_none()
-        {
+        let preprocessed_reward_set =
+            SortitionDB::get_preprocessed_reward_set(&mut tx, &first_prepare_sn.sortition_id)?;
+        let need_to_store = if let Some(reward_cycle_info) = preprocessed_reward_set {
```
Comment (kantai) [inline stackslib/src/chainstate/coordinator/mod.rs:850]: Can you add a bit more inline comment here about what issue this change fixes and how? I think what’s happening here is that (1) the chains coordinator can first mark a reward set as unknown and then it gets stored there, and then (2) when it gets recomputed after the anchor block arrives, this check allows it to overwrite.

Does this PR have a regression test for this behavior?

Comment (jcnelson) [reply stackslib/src/chainstate/coordinator/mod.rs:850]: Technically, yes -- a slew of other tests would fail to run if this behavior wasn't added (namely, the downloader tests would all spin forever for want of a computed reward cycle)

File: stackslib/src/chainstate/burn/db/sortdb.rs (hunk 1 above)
Comment (jcnelson) [reply stackslib/src/chainstate/burn/db/sortdb.rs:4681]: Sure

File: stackslib/src/chainstate/coordinator/mod.rs (hunk 3 above)
Comment (jcnelson) [reply stackslib/src/chainstate/coordinator/mod.rs:850]: They began to stall once we removed the aggregate public key and began to instead rely on inspecting the three most recent reward sets directly in order to obtain the keys needed to authenticate downloaded blocks.  The stall was induced by the changes in the PR into which this PR is targeted.

Comment (kantai) [reply stackslib/src/chainstate/coordinator/mod.rs:850]: Okay, that makes sense.

This code block just needs some more comments then.

Comment (jcnelson) [reply stackslib/src/chainstate/coordinator/mod.rs:858]: Done

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 4]
```diff
@@ -3542,59 +3541,139 @@ impl SortitionDB {
...
+        let sql = "REPLACE INTO preprocessed_reward_sets (sortition_id,reward_set) VALUES (?1,?2)";
         let rc_json = serde_json::to_string(rc_info).map_err(db_error::SerializationError)?;
         let args: &[&dyn ToSql] = &[sortition_id, &rc_json];
         sort_tx.execute(sql, args)?;
         Ok(())
     }
 
+    /// Get the prepare phase start sortition ID of a reward cycle
+    fn inner_get_prepare_phase_start_sortition_id_for_reward_cycle(
+        index_conn: &SortitionDBConn,
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3553]: Rather than `Self::inner_*` for these functions, it'd be simpler to just make these instance functions of SortitionDBConn, then there wouldn't be a namespace overlap and they could just be called `get...()`, and they'd be less verbose to invoke.

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 5]
```diff
@@ -3542,59 +3541,139 @@ impl SortitionDB {
...
+                    "tip_sortition_id" => %tip,
+                    "reward_cycle_id" => reward_cycle_id,
+                    "prepare_phase_start_height" => prepare_phase_start
+                );
+                db_error::NotFoundError
+            })?;
+        Ok(first_sortition)
+    }
+
+    pub fn get_prepare_phase_start_sortition_id_for_reward_cycle(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3576]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 6]
```diff
@@ -3542,59 +3541,139 @@ impl SortitionDB {
...
+        );
+
+        Ok((
+            Self::get_preprocessed_reward_set(index_conn, &first_sortition)?
+                .ok_or(db_error::NotFoundError)?,
+            first_sortition,
+        ))
+    }
+
+    pub fn get_preprocessed_reward_set_for_reward_cycle(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3619]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 7]
```diff
@@ -3542,59 +3541,139 @@ impl SortitionDB {
...
+            pox_constants,
+            first_block_height,
+            tip,
+            reward_cycle_id,
+        )
+        .and_then(|(reward_cycle_info, _anchor_sortition_id)| Ok(reward_cycle_info))
+    }
 
-        let first_sortition = get_ancestor_sort_id(
+    pub fn get_preprocessed_reward_set_of(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3667]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 8]
```diff
@@ -3842,6 +3921,46 @@ impl<'a> SortitionDBConn<'a> {
             serde_json::from_str(&pox_addrs_json).expect("FATAL: failed to decode pox payout JSON");
         Ok(pox_addrs)
     }
+
+    pub fn get_prepare_phase_start_sortition_id_for_reward_cycle(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3925]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 9]
```diff
@@ -3842,6 +3921,46 @@ impl<'a> SortitionDBConn<'a> {
...
+        SortitionDB::inner_get_prepare_phase_start_sortition_id_for_reward_cycle(
+            self,
+            &self.context.pox_constants,
+            self.context.first_block_height,
+            tip,
+            reward_cycle_id,
+        )
+    }
+
+    pub fn get_preprocessed_reward_set_for_reward_cycle(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3939]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 10]
```diff
@@ -3842,6 +3921,46 @@ impl<'a> SortitionDBConn<'a> {
...
+        SortitionDB::inner_get_preprocessed_reward_set_for_reward_cycle(
+            self,
+            &self.context.pox_constants,
+            self.context.first_block_height,
+            tip,
+            reward_cycle_id,
+        )
+    }
+
+    pub fn get_preprocessed_reward_set_of(
```
Comment (kantai) [inline stackslib/src/chainstate/burn/db/sortdb.rs:3953]: Can you add a docstring for the pub fns?

File: stackslib/src/chainstate/stacks/boot/mod.rs [hunk 11]
```diff
@@ -40,7 +40,9 @@ use serde::Deserialize;
 use stacks_common::address::AddressHashMode;
 use stacks_common::codec::StacksMessageCodec;
 use stacks_common::types;
-use stacks_common::types::chainstate::{BlockHeaderHash, StacksAddress, StacksBlockId};
+use stacks_common::types::chainstate::{
+    BlockHeaderHash, StacksAddress, StacksBlockId, StacksPublicKey,
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/mod.rs:44]: Is StacksPublicKey used here?

File: stackslib/src/net/p2p.rs [hunk 12]
```diff
@@ -259,13 +258,10 @@ pub struct PeerNetwork {
...
-    /// Only active during epoch 3.x and beyond.
-    /// Gets refreshed on each new Stacks block arrival, which deals with burnchain forks.
-    /// Stored in a BTreeMap because we often need to query the last or second-to-last reward cycle
-    /// aggregate public key, and we need to determine whether or not to load new reward cycles'
-    /// keys.
-    pub aggregate_public_keys: BTreeMap<u64, Option<Point>>,
+    /// The reward sets of the current and past reward cycle.
+    /// Needed to validate blocks, which are signed by a threshold of stackers
+    pub current_reward_sets: BTreeMap<u64, RewardCycleInfo>,
+    pub current_reward_set_ids: BTreeMap<u64, SortitionId>,
```
Comment (kantai) [inline stackslib/src/net/p2p.rs:264]: What are `current_reward_set_ids`? Can you add a docstring?

File: stackslib/src/net/p2p.rs [hunk 13]
```diff
@@ -5430,58 +5427,100 @@ impl PeerNetwork {
...
-                        false,
+                    e
+                })
+            else {
+                // NOTE: this should never be reached
+                continue;
+            };
+            if !reward_cycle_info.is_reward_info_known() {
+                // haven't yet processed the anchor block, so don't store
+                test_debug!("Reward cycle info for cycle {} at sortition {} expects the PoX anchor block, so will not cache", rc, &reward_cycle_sort_id);
```
Comment (kantai) [inline stackslib/src/net/p2p.rs:5476]: Should be info or debug?

File: stackslib/src/net/p2p.rs [hunk 14]
```diff
@@ -5430,58 +5427,100 @@ impl PeerNetwork {
...
-                        sortdb,
-                        &ih,
-                        chainstate,
-                        self.burnchain.reward_cycle_to_block_height(key_rc),
-                        &stacks_tip_block_id,
-                        false,
+                    e
+                })
+            else {
+                // NOTE: this should never be reached
```
Comment (kantai) [inline stackslib/src/net/p2p.rs:5471]: Should `error!` and raise a net_error?

File: stackslib/src/net/p2p.rs [hunk 15]
```diff
@@ -5430,58 +5427,100 @@ impl PeerNetwork {
...
+            }
+
+            test_debug!(
+                "Reward cycle info for cycle {} at sortition {} is {:?}",
+                rc,
+                &reward_cycle_sort_id,
+                &reward_cycle_info
+            );
+            self.current_reward_sets.insert(rc, reward_cycle_info);
+            self.current_reward_set_ids.insert(rc, reward_cycle_sort_id);
```
Comment (kantai) [inline stackslib/src/net/p2p.rs:5487]: Would `current_reward_sets: BTreeMap<u64, (SortitionId, RewardCycleInfo)>` work for tracking the information? Or is there a case where `current_reward_sets.get(x).is_some() && current_reward_set_ids.get(x).is_none()`?

File: testnet/stacks-node/src/nakamoto_node/miner.rs [hunk 16]
```diff
@@ -291,25 +287,26 @@ impl BlockMinerThread {
...
+        // NOTE: this is a placeholder until the API can be fixed
+        let aggregate_public_key = {
+            let key_bytes = [
+                0x03, 0xd3, 0xe1, 0x5a, 0x36, 0xf3, 0x2a, 0x9e, 0x71, 0x31, 0x7f, 0xcb, 0x4a, 0x20,
+                0x1b, 0x0c, 0x08, 0xb3, 0xbc, 0xfb, 0xdc, 0x8a, 0xee, 0x2e, 0xe4, 0xd2, 0x69, 0x23,
+                0x00, 0x06, 0xb1, 0xa0, 0xcb,
+            ];
+            let ecdsa_pk = ecdsa::PublicKey::try_from(key_bytes.as_slice()).unwrap();
+            Point::try_from(&Compressed::from(ecdsa_pk.to_bytes())).unwrap()
         };
```
Comment (hstove) [inline testnet/stacks-node/src/nakamoto_node/miner.rs:299]: Why this instead of `Point::new()`?

**Review by hstove — APPROVED** [review]
Overall LGTM! I appreciate the discrete commits, it made it easier to review. Also good work with the improvements of the API for fetching a reward set.

**Review by kantai — COMMENTED** [review]
Overall LGTM, just a few comments.

File: testnet/stacks-node/src/nakamoto_node/miner.rs (hunk 16 above)
Comment (jcnelson) [reply testnet/stacks-node/src/nakamoto_node/miner.rs:299]: Because I didn't know `Point::new()` was a thing :)  I'll update

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 17]
```diff
@@ -4559,12 +4678,14 @@ impl SortitionDB {
         Ok(ret)
     }
 
+    /// DO NOT CALL during Stacks block processing (including during Clarity VM evaluation). This function returns the latest data known to the node, which may not have been at the time of original block assembly.
```
Comment (jferrant) [inline stackslib/src/chainstate/burn/db/sortdb.rs:4681]: This is just for my own knowledge, not a nit: I am not entirely sure I understand what this means? Could you explain a tiny bit more for me?

File: stackslib/src/net/p2p.rs [hunk 18]
```diff
@@ -5430,58 +5427,100 @@ impl PeerNetwork {
...
+        }
+
+        // free memory
+        if self.current_reward_sets.len() > 3 {
```
Comment (jferrant) [inline stackslib/src/net/p2p.rs:5491]: This would be nicer in a separate function I think. Could also then make a small unit test for it.

File: stackslib/src/net/tests/download/nakamoto.rs [hunk 19]
```diff
@@ -444,10 +443,22 @@ fn test_nakamoto_unconfirmed_tenure_downloader() {
         let mut utd = NakamotoUnconfirmedTenureDownloader::new(naddr.clone(), Some(tip_block_id));
         assert_eq!(utd.state, NakamotoUnconfirmedDownloadState::GetTenureInfo);
 
-        utd.confirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
-        utd.unconfirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
+        utd.confirmed_signer_keys = Some(
```
Comment (jferrant) [inline stackslib/src/net/tests/download/nakamoto.rs:446]: This is a total nit (epsecially since this is a test), but it prob is slightly faster to just do this lookup once and then assign `utd.uncornfirmed_signer_keys = utd.confirmed_signer_keys.clone();`

File: stackslib/src/net/tests/download/nakamoto.rs [hunk 20]
```diff
@@ -507,10 +518,22 @@ fn test_nakamoto_unconfirmed_tenure_downloader() {
 
         let mut utd =
             NakamotoUnconfirmedTenureDownloader::new(naddr.clone(), Some(mid_tip_block_id));
-        utd.confirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
-        utd.unconfirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
+        utd.confirmed_signer_keys = Some(
```
Comment (jferrant) [inline stackslib/src/net/tests/download/nakamoto.rs:521]: Same as above comment. Nit, but could just assign `utd.unconfirmed_signer_keys = utd.confirmed_signer_keys;`

File: stackslib/src/net/tests/download/nakamoto.rs [hunk 21]
```diff
@@ -596,10 +619,22 @@ fn test_nakamoto_unconfirmed_tenure_downloader() {
...
```
Comment (jferrant) [inline stackslib/src/net/tests/download/nakamoto.rs:622]: Same nit. `utd.unconfirmed_signer_keys = utd.confirmed_signer_keys.clone();`

File: stackslib/src/net/tests/download/nakamoto.rs [hunk 22]
```diff
@@ -684,10 +719,22 @@ fn test_nakamoto_unconfirmed_tenure_downloader() {
     // serve all of the unconfirmed blocks in one shot.
     {
         let mut utd = NakamotoUnconfirmedTenureDownloader::new(naddr.clone(), None);
-        utd.confirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
-        utd.unconfirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
+        utd.confirmed_signer_keys = Some(
```
Comment (jferrant) [inline stackslib/src/net/tests/download/nakamoto.rs:722]: same nit. `utd.unconfirmed_signer_keys = utd.confirmed_signer_keys.clone();`

File: stackslib/src/net/tests/download/nakamoto.rs [hunk 23]
```diff
@@ -751,10 +798,22 @@ fn test_nakamoto_unconfirmed_tenure_downloader() {
     // bad block signature
     {
         let mut utd = NakamotoUnconfirmedTenureDownloader::new(naddr.clone(), None);
-        utd.confirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
-        utd.unconfirmed_aggregate_public_key =
-            Some(agg_pubkeys.get(&tip_rc).cloned().unwrap().unwrap());
+        utd.confirmed_signer_keys = Some(
```
Comment (jferrant) [inline stackslib/src/net/tests/download/nakamoto.rs:801]: Same nit. `utd.unconfirmed_signer_keys = utd.confirmed_signer_keys.clone();`

**Comment by jferrant** [comment]
I really only have non blocking nits. aside from that, if we don;t plan to keep v1 tests in working state, might want to remove filter_bad_transactions from CI. Otherwise, maybe we can maintain this test?

File: stackslib/src/chainstate/burn/db/sortdb.rs [hunk 24]
```diff
@@ -3646,8 +3646,12 @@ impl SortitionDB {
             db_error::NotFoundError
         })?;
 
+        // NOTE: the .saturating_sub(1) is necessary because the reward set is calculated in epoch
+        // 2.5 and lower at reward cycle index 1, not 0.  This correction ensures that the last
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/chainstate/burn/db/sortdb.rs:3650]: The reward set for a reward cycle is calculated in block 1, not block 0 (i.e. the _second_ block) of a reward cycle.  That is, if your reward cycle length is 10, and the system start height is 0, then reward cycles begin at heights 10, 20, 30, 40, ..etc, but the reward sets are calculated at heights 11, 21, 31, 41, ...etc.  Aaron has been calling the offset into the reward cycle the _reward cycle index_, which is a term I re-used here.  This is only true for epoch 2.5 and earlier.  In Nakamoto, they're calculated when the first prepare-phase block is processed.

File: stackslib/src/chainstate/burn/db/sortdb.rs (hunk 4 above)
Comment (jcnelson) [reply stackslib/src/chainstate/burn/db/sortdb.rs:3553]: Sure

**Review by hstove — APPROVED** [review]

File: stackslib/src/chainstate/burn/db/sortdb.rs (hunk 17 above)
Comment (jferrant) [reply stackslib/src/chainstate/burn/db/sortdb.rs:4654]: Ah that makes sense! thank you :D
