### PR TITLE
Fix: Wait until in nakamoto to shutdown 2.x block downloader #5676

### LINKED ISSUE #5676: Testnet: unable to sync from genesis
When syncing from genesis on testnet, the node stalls at burn block `2700`, and stacks block `255`. It prints the following message repeatedly:
```
{"msg":"Process burn block 2701 reward cycle 3 in /hirosystems/data/krypton/burnchain","level":"INFO","ts":"2025-01-09T18:55:40.201743228Z","thread":"chains-coordinator-0.0.0.0:20443","line":1085,"file":"stackslib/src/chainstate/nakamoto/coordinator/mod.rs","burn_block_hash":"35616f7bc3039a6f5c33caf089031824f530f2ef75a77a04459750ee2382ff5e","is_prior_in_prepare_phase":true,"is_rc_start":true,"in_prepare_phase":false}
{"msg":"No PoX anchor block known yet for cycle 3","level":"INFO","ts":"2025-01-09T18:55:40.320665578Z","thread":"chains-coordinator-0.0.0.0:20443","line":527,"file":"stackslib/src/chainstate/nakamoto/coordinator/mod.rs"}
{"msg":"Missing canonical anchor block","level":"ERRO","ts":"2025-01-09T18:55:40.320710088Z","thread":"chains-coordinator-0.0.0.0:20443","line":752,"file":"stackslib/src/chainstate/nakamoto/coordinator/mod.rs"}
```

This should be easy to replicate locally, as it just requires running a stacks node on version `3.1.0.0.2`.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #5676 by requiring the p2p thread's view of the Stacks tip to be a Nakamoto tip before shutting down the epoch 2.x block download state machines.

### CODE REVIEW

File: stackslib/src/net/p2p.rs [hunk 1]
```diff
@@ -3606,12 +3606,7 @@ impl PeerNetwork {
 
             // in Nakamoto epoch, but we might still be doing epoch 2.x things since Nakamoto does
             // not begin on a reward cycle boundary.
-            if cur_epoch.epoch_id == StacksEpochId::Epoch30
-                && (self.burnchain_tip.block_height
-                    <= cur_epoch.start_height
-                        + u64::from(self.burnchain.pox_constants.reward_cycle_length)
-                    || self.connection_opts.force_nakamoto_epoch_transition)
-            {
+            if cur_epoch.epoch_id >= StacksEpochId::Epoch30 && !self.stacks_tip.is_nakamoto {
```
Comment (kantai) [inline stackslib/src/net/p2p.rs:3609]: Can you update the comment above this line to say something like `In nakamoto, but our stacks tip is still an epoch 2.x block, so we may need to download more 2.x blocks before cutting over entirely to nakamoto`?

**Review by jferrant — APPROVED** [review]

**Review by kantai — CHANGES_REQUESTED** [review]
This makes sense to me, but please add a unit test to cover this change.

File: stackslib/src/net/p2p.rs (hunk 1 above)
Comment (jcnelson) [reply stackslib/src/net/p2p.rs:3609]: Sure

**Comment by CharlieC3** [comment]
Can confirmed this has fixed a couple nodes we're syncing from genesis on testnet!

**Review by CharlieC3 — APPROVED** [review]
:shipit: Pending Aaron's comment.

**Review by obycode — DISMISSED** [review]

File: stackslib/src/net/mod.rs [hunk 2]
```diff
@@ -3325,6 +3329,19 @@ pub mod test {
...
+                    self.network.nakamoto_state_machine_passes,
+                    nakamoto_passes + 1
+                );
+            }
+            if self
+                .network
+                .need_epoch2_state_machines(self.network.get_current_epoch().epoch_id)
+            {
+                assert_eq!(self.network.epoch2_state_machine_passes, epoch2_passes + 1);
+            }
```
Comment (kantai) [inline stackslib/src/net/mod.rs:3343]: While this is a pretty limited case, this kind of check in a test undermines the test. If you replace the implementation of `need_epoch2_state_machines()` with just ` { false } `, the test would pass.

You could inline the condition like:

```rust
            if self.network.get_current_epoch().epoch_id >= StacksEpochId::Epoch30 {
                assert_eq!(
                    self.network.nakamoto_state_machine_passes,
                    nakamoto_passes + 1
                );
                let epoch2_expected_passes = if self.stacks_tip.is_nakamoto {
                    epoch2_passes
                } else {
                    epoch2_passes + 1
                }
                assert_eq!(self.network.epoch2_state_machine_passes, epoch2_expected_passes);
            }
```

That at least would get the test to fail when a simple mutation is applied.

**Review by kantai — COMMENTED** [review]
I think the test checks should be updated. This also should get a changelog entry.

File: stackslib/src/net/mod.rs (hunk 2 above)
Comment (jcnelson) [reply stackslib/src/net/mod.rs:3343]: Yup, great points. Will address.

Comment (jcnelson) [reply stackslib/src/net/mod.rs]: Done

**Review by obycode — APPROVED** [review]

**Review by kantai — APPROVED** [review]

**Review by jferrant — DISMISSED** [review]

**Comment by obycode** [comment]
Confirmed. `net::tests::inv::nakamoto::test_nakamoto_inv_sync_across_epoch_change` is hanging forever locally as well.

**Review by kantai — CHANGES_REQUESTED** [review]
The unit test @obycode mentions needs to be fixed.

**Review by obycode — APPROVED** [review]

**Review by obycode — DISMISSED** [review]
Unit test is still failing.

**Comment by jcnelson** [comment]
Unit tests pass locally for me; checking to see if they now pass CI.

**Review by kantai — APPROVED** [review]
