### PR TITLE
Fix sip 031 test flakiness and refactoring of base types and functions

### LINKED ISSUE #6327: [Refactor] move SIP-031 coinbase code alongside that of SIP-029
The code for SIP-031 currently lives in `stackslib/src/chainstate/nakamoto/mod.rs`, and is heavily based on the code we used for the SIP-029 coinbase emission changes.  However, the SIP-029 code lives in `stacks-common/src/types/mod.rs`.  We should put the SIP-031 code and SIP-029 code into the same modules, since they're semantically related -- they both describe how to compute the coinbase for a new tenure and provide similar testing facilities for using variations of their respective emission schedules.

### PR DESCRIPTION
**Pull request by rdeioris**
### Description

This patch fixes potential flakiness in sip-031 related integration tests (caused by the usage of get_latest_block_proposal instead of  test_observer::get_blocks()) and moves the basic sip-031-related types and functions from stackslib to stacks-common 

### Applicable issues

- fixes #6327 

### Checklist

- [ ] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [ ] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

**Comment by jferrant** [comment]
miner_constructs_replay_block is broken on develop. Hangs forever. So do not think this is a problem with this PR. I also see it failing on other PRs.

File: stacks-common/src/types/mod.rs [hunk 1]
```diff
@@ -254,6 +254,181 @@ impl CoinbaseInterval {
...
+    }
+}
+
+impl SIP031EmissionInterval {
+    /// Look up the amount of STX to emit at the start of the tenure at the specified height.
+    /// Precondition: `intervals` must be sorted in descending order by `start_height`
+    pub fn get_sip_031_emission_at_height(burn_height: u64, mainnet: bool) -> u128 {
+        let intervals = get_sip_031_emission_schedule(mainnet);
+
+        if intervals.is_empty() {
```
Comment (jferrant) [inline stacks-common/src/types/mod.rs:401]: Just a nit but this is an unnecessary check. Could just let the function fall through.

**Review by obycode — APPROVED** [review]
lgtm!
