### PR TITLE
Fix: 5159, 5169, 5171, 5172, and others

### LINKED ISSUE #5159: [Network] inbound neighbor walk is broken
It appears that there has been a behavioral regression in the node's neighbor walk algorithm.  It ought to be the case that if node A contacts node B, then node B should attempt to contact node A, and if successful, add node A to its outbound peer set (making it eligible for data pushed from node B, and eligible for enumeration in response to a `GetNeighbors` p2p message).  This isn't happening anymore.

### LINKED ISSUE #5169: [Network] PeerDB should enforce at most one row per public key hash
Due to node churn, especially in NAT'ed automated clusters, it's possible that the same peer can be represented in multiple rows while having the same public key.  Unfortunately, this isn't as simple as declaring the public key to be the primary key due to the way the PeerDB is structured.

### LINKED ISSUE #5171: [Network] GetNeighbors reply should alternate between including public-only versus public/private IPs
For a variety of reasons, nodes may need to report private IP ranges to each other on neighbor walk (e.g. so nodes in a cluster can find each other).  However, this is useless for downstream nodes.  To address this without changing the protocol, the node should alternate (with some configurable probability) between reporting public-only neighbors and a mix of public/private nodes.

### LINKED ISSUE #5172: [nakamoto] Bug in `/v2/neighbors`
Copying over from Nakamoto Slack, as reported by @jcnelson:

There's a bug in `/v2/neighbors` -- it's reporting all neighbors whose last-contact time is greater than `self.connection_opts.max_neighbor_age` (which is sometime in January 1970 if taken as an absolute UNIX timestamp), whereas the p2p interfaces all use `get_epoch_time_secs()` - `self.connection_opts.max_neighbor_age` (which is correct).  `self.connection_opts.max_neighbor_age` is set to 3 days.  Some addresses reported in /v2/neighbors may be dead

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes a few reported issues in the neighbor walk state machine, as well as a few unreported / privately requested ones:

* It fixes #5159 by making it so that a node whose always-allowed (i.e. seed) peers are unavailable (or misconfigured) can still discover neighbors when not in IBD mode.

* It fixes #5169 by collating queries to the `frontier` table by public key and reporting the one with the latest contact time.  The overall schema of `frontier` remains the same out of necessity to avoid both DoS and eclipse attacks.

* It fixes #5171 by classifying rows in the `frontier` table as public (or not) based on whether or not they're in known-private IPv4 or IPv6 address prefixes, and then having the `GetNeighbors` handler decide at random as to whether or not to exclude private neighbors in its `Neighbors` response.

* It fixes #5172 simply by changing the `max_age` calculation in the query to find recent neighbors

* It adds `[connection_opts].log_neighbor_freq` to allow the node operator to log all p2p conversations to `DEBG`-level logs every so often (value is in milliseconds).  Default is once every minute.

* It adds `[connection_opts].walk_seed_probability` to allow the node operator to control the degree to which the node will walk to non-seed nodes (instead of retrying the seed nodes) when not in IBD mode and when no seed nodes are connected.  The default is 10%.

* It fixes a bug in the neighbor storage logic whereby neighbor rows aren't always updated on discovery or handshake, causing the node to rely on stale neighbor data (including stale assessments of the neighbor's in/out degrees, which hampers neighbor walk).

* It uses `sort_unstable_by()` in `stackslib/src/net/prune.rs` to avoid a node crash when two nodes are ranked as equally healthy, which is a problem that has only recently manifested in large-scale testing.

* It reduces the traffic volume in StackerDB replication by checking a message's `rc_consensus_hash` value against the peer's last-computed `rc_consensus_hash` value, so that messages that are locally stale are not propagated

* It fixes a bug in stepping to a neighbor with a private address when the node itself reports private but routable address as its socket's peer address.  This caused the node to store the wrong address for the private neighbor (namely, it would store the ephemeral port from the peer address instead of the protocol-reported port).

* It updates logging in the StackerDB sync state machine to always report the local peer address and the contract address in question, which makes it easier to debug state machines when the node replicates multiple StackerDBs.

* It fixes the neighbor-walk tests so that small-scale tests can now run as unit tests (and are no longer `#[ignore]`d), and moves large-scale topology tests into integration tests (in `tests::p2p::convergence`) so they can run in parallel without clobbering ports.  I don't know how well they'll behave because they need an open file limit of 4096 to run, but it seems #5190 might address this.

----

The majority of line noise from this PR comes from that last test refactoring above.  Also, in order to get it to build as an integration test, I had to switch a lot of `#[cfg(test)]` statements to `#[cfg(any(test, feature = "testing"))]`.  This affected many files.

### CODE REVIEW

**Comment by jcnelson** [comment]
Putting this as a draft for now.  I'm testing this live on mainnet and on Nakamoto testnet and I've noticed a couple problems I'll address in this PR.

File: stackslib/src/burnchains/tests/mod.rs [hunk 1]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/burnchains/tests/mod.rs:16]: Please remove -- unused code should generate warnings.

File: stackslib/src/chainstate/coordinator/tests.rs [hunk 2]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/coordinator/tests.rs:16]: Please remove

File: stackslib/src/chainstate/nakamoto/coordinator/tests.rs [hunk 3]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/nakamoto/coordinator/tests.rs:16]: Please remove

File: stackslib/src/chainstate/nakamoto/tests/mod.rs [hunk 4]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/nakamoto/tests/mod.rs:16]: Please remove

File: stackslib/src/chainstate/stacks/boot/mod.rs [hunk 5]
```diff
@@ -1379,19 +1379,20 @@ impl StacksChainState {
...
+#[cfg(any(test, feature = "testing"))]
 pub mod pox_4_tests;
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub mod signers_tests;
 
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub mod test {
+    #![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/mod.rs:1395]: Please remove

File: stackslib/src/chainstate/stacks/boot/pox_2_tests.rs [hunk 6]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/pox_2_tests.rs:16]: Please remove

File: stackslib/src/chainstate/stacks/boot/pox_3_tests.rs [hunk 7]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/pox_3_tests.rs:16]: Please remove

File: stackslib/src/chainstate/stacks/boot/pox_4_tests.rs [hunk 8]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/pox_4_tests.rs:16]: Please remove

File: stackslib/src/chainstate/stacks/boot/signers_tests.rs [hunk 9]
```diff
@@ -13,6 +13,7 @@
 //
 // You should have received a copy of the GNU General Public License
 // along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/boot/signers_tests.rs:16]: Please remove

File: stackslib/src/chainstate/stacks/db/blocks.rs [hunk 10]
```diff
@@ -6936,8 +6936,9 @@ impl StacksChainState {
     }
 }
 
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub mod test {
+    #![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/db/blocks.rs:6941]: Please remove

File: stackslib/src/chainstate/stacks/db/mod.rs [hunk 11]
```diff
@@ -2713,8 +2713,9 @@ impl StacksChainState {
     }
 }
 
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub mod test {
+    #![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/db/mod.rs:2718]: Please remove

File: stackslib/src/chainstate/stacks/db/transactions.rs [hunk 12]
```diff
@@ -1571,6 +1571,7 @@ impl StacksChainState {
 
 #[cfg(test)]
 pub mod test {
+    #![allow(unused)]
```
Comment (kantai) [inline stackslib/src/chainstate/stacks/db/transactions.rs:1574]: Please remove

**Comment by jcnelson** [comment]
@kantai Do you think it is a good use of time to go and patch the thousands of lines of test-only code where there are unused variables?

File: stackslib/src/net/download/epoch2x.rs [hunk 13]
```diff
@@ -56,22 +56,22 @@ use crate::net::{
...
 pub const BLOCK_DOWNLOAD_BAN_URL: u64 = 60;
 
 /// If we created a request to download a block or microblock, don't do so again until this many
 /// seconds have passed.
-#[cfg(not(test))]
+#[cfg(not(any(test, feature = "testing")))]
 pub const BLOCK_REREQUEST_INTERVAL: u64 = 60;
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub const BLOCK_REREQUEST_INTERVAL: u64 = 30;
```
Comment (kantai) [inline stackslib/src/net/download/epoch2x.rs:75]: These are kind of scary to me -- the `testing` feature is a default feature for `debug` builds (not just test builds), so changing the values of constants for all `debug` builds could have some unintended consequences.

File: stackslib/src/core/mod.rs [hunk 14]
```diff
@@ -68,9 +68,9 @@ pub const GENESIS_EPOCH: StacksEpochId = StacksEpochId::Epoch20;
 /// The number of blocks which will share the block bonus
 ///   from burn blocks that occurred without a sortition.
 ///   (See: https://forum.stacks.org/t/pox-consensus-and-stx-future-supply)
-#[cfg(test)]
+#[cfg(any(test, feature = "testing"))]
 pub const INITIAL_MINING_BONUS_WINDOW: u16 = 10;
-#[cfg(not(test))]
+#[cfg(not(any(test, feature = "testing")))]
 pub const INITIAL_MINING_BONUS_WINDOW: u16 = 10_000;
```
Comment (kantai) [inline stackslib/src/core/mod.rs:74]: This is pretty scary to me -- the `testing` feature is enabled by default for `debug` builds in the `stacks-node`, meaning this constant would change depending on whether or not you built `stacks-node` as `--release`.

File: testnet/stacks-node/src/tests/p2p/convergence.rs
Comment (kantai) [inline testnet/stacks-node/src/tests/p2p/convergence.rs:1]: These tests appear to only use the `TestPeer` harness -- could these tests live the `stackslib` crate? If so, almost all of the `cfg(feature = "testing")` changes could be avoided, right?

File: stackslib/src/net/download/epoch2x.rs (hunk 13 above)
Comment (jcnelson) [reply stackslib/src/net/download/epoch2x.rs:75]: >  the testing feature is a default feature for debug builds (not just test builds),

I did not know that.  That sounds like a bug -- `"testing"` is supposed to activate test-only code paths in dependent crates, I thought?

File: testnet/stacks-node/src/tests/p2p/convergence.rs
Comment (jcnelson) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: The problem is that `TestPeer` depends on basically everything else in `stackslib`

File: stackslib/src/net/download/epoch2x.rs (hunk 13 above)
Comment (jcnelson) [reply stackslib/src/net/download/epoch2x.rs:75]: Can you show me where `"testing"` is an enabled feature for debug builds?  Because, AFAIK that was never supposed to be the case.

Comment (kantai) [reply stackslib/src/net/download/epoch2x.rs:75]: It's codepaths intended for running only in tests, but cargo doesn't have an option for "enable feature only in testing" (see maybe this issue: https://github.com/rust-lang/cargo/issues/8379), so the workaround is to enable it by default for debug builds. I totally agree that its a footgun, though, and I think we should try to deprecate the `testing` feature.

File: testnet/stacks-node/src/tests/p2p/convergence.rs
Comment (kantai) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: Yeah-- I'm saying move these tests to `stackslib`, they don't appear to need anything from `stacks-node`

Comment (jcnelson) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: That's where they originally were.  They can't run as unit tests though -- they (1) require too many file descriptors and (2) can't run in parallel.  So, we just weren't running them.

Comment (jcnelson) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: The problem is that no matter where it lives, we have to expose `TestPeer` and everything it depends on to `stacks-node`, so that integration tests in `stacks-node` can call them.

Comment (kantai) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: But the only integration tests in `stacks-node` that call `TestPeer` are these new ones, which don't depend on `stacks-node` -- if you move them back to `stackslib`, we can invoke them as integration tests from there instead.

e.g., instead of the integration test runners invoking

```
cargo test --bin=stacks-node ... p2p::convergence::test_foo -- --ignored
```

they'd invoke

```
cargo test -p stackslib ... p2p::convergence::test_foo -- --ignored
```

That might require some CI action updates, but I think that'd be preferable to all the `testing` features this PR requires.

File: stackslib/src/net/download/epoch2x.rs (hunk 13 above)
Comment (kantai) [reply stackslib/src/net/download/epoch2x.rs:75]: > Can you show me where "testing" is an enabled feature for debug builds? Because, AFAIK that was never supposed to be the case.

https://github.com/stacks-network/stacks-core/blob/master/testnet/stacks-node/Cargo.toml#L43-L45

It's basically they only way to invoke "test" code from a separate crate's tests for the reasons I mentioned above.

File: testnet/stacks-node/src/tests/p2p/convergence.rs
Comment (jcnelson) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: I can do this with @wileyj's help.  @wileyj If I take a stab at this, can you finish it off if there are errors?

File: stackslib/src/net/download/epoch2x.rs (hunk 13 above)
Comment (kantai) [reply stackslib/src/net/download/epoch2x.rs:75]: Ah -- nevermind, you are right. `[dev-dependencies]` only gets used for test builds, examples, docs, and benchmarks. I assumed that `profile.dev` builds also used them (probably because of the name?) but that's not the case. After applying this patch:

```git
diff --git a/testnet/stacks-node/src/main.rs b/testnet/stacks-node/src/main.rs
index fcdc9f584..b55006b56 100644
--- a/testnet/stacks-node/src/main.rs
+++ b/testnet/stacks-node/src/main.rs
@@ -281,6 +281,10 @@ fn main() {
 
     let mut args = Arguments::from_env();
     let subcommand = args.subcommand().unwrap().unwrap_or_default();
+    if subcommand.as_str() == "test-build" {
+        info!("build: {}. block_request_int = {}", version(), stacks::net::download::epoch2x::BLOCK_REREQUEST_INTERVAL);
+        return;
+    }
 
     info!("{}", version());
```

And running:
```
% cargo run --bin=stacks-node -- test-build  
   ...
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.12s
     Running `target/debug/stacks-node test-build`
INFO [1726508395.509174] [testnet/stacks-node/src/main.rs:285] [main] build: stacks-node 0.1.0 (:, debug build, macos [aarch64]). block_request_int = 60
```

**Review by kantai — COMMENTED** [review]
This LGTM, but I think we'd be better off if the `p2p::convergence` tests stayed in `net::tests::neighbors`, and we just updated the CI to add another integration test job to execute them there (instead of in `stacks-node`).

**Comment by wileyj** [comment]
> This LGTM, but I think we'd be better off if the `p2p::convergence` tests stayed in `net::tests::neighbors`, and we just updated the CI to add another integration test job to execute them there (instead of in `stacks-node`).

unless this is needed to merge this PR, can you open an issue and we'll take that off your pile?

**Comment by jcnelson** [comment]
> unless this is needed to merge this PR, can you open an issue and we'll take that off your pile?

I'd like it in this PR.  We need to have been running these tests the whole time; we would have caught some of these problems earlier if we did.

**Comment by wileyj** [comment]
> > unless this is needed to merge this PR, can you open an issue and we'll take that off your pile?
> 
> I'd like it in this PR. We needed to have been running these tests the whole time; we would have caught some of these problems earlier if we did.

👍 
let me know where i can help and you'll have it

File: testnet/stacks-node/src/tests/p2p/convergence.rs
Comment (wileyj) [reply testnet/stacks-node/src/tests/p2p/convergence.rs:1]: i'm not entirely certain what changes in ci would be needed here, but i can look/help as needed

**Review by kantai — APPROVED** [review]

**Review by obycode — APPROVED** [review]
