### PR TITLE
Ctrl-C graceful shutdown during burnchain initialization 

### LINKED ISSUE #4423: Crash when network connectivity lost
This doesn't happen every time the network connection is lost, but tonight when I was syncing a `next` node to mainnet using my phone's wifi hotspot and went out of range, the following crash occurred.

Low prio ticket, just documenting that it happened.

```
INFO [1708706569.491401] [stackslib/src/chainstate/stacks/db/transactions.rs:678] [chains-coordinator-0.0.0.0:20443] Post-condition check failure on non-fungible asset SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.citadels::citadels owned by SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-art-market-v2: UInt(2091) Sent
INFO [1708706569.491417] [stackslib/src/chainstate/stacks/db/transactions.rs:1063] [chains-coordinator-0.0.0.0:20443] Contract-call aborted by post-condition, contract_name: SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-art-market-v2, function_name: buy-item, function_args: [SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.citadels, u9, u2091]
ERRO [1708706575.556707] [testnet/stacks-node/src/main.rs:268] [chain-liveness-0.0.0.0:20443] Process abort due to thread panic: panicked at testnet/stacks-node/src/config.rs:1916:51:
called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }
ERRO [1708706575.950600] [testnet/stacks-node/src/main.rs:270] [chain-liveness-0.0.0.0:20443] Panic backtrace:    0: stacks_node::main::{{closure}}
             at src/main.rs:269:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   5: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   7: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
      stacks_node::config::NodeConfig::add_bootstrap_node
             at src/config.rs:1916:24
      stacks_node::config::NodeConfig::set_bootstrap_nodes
             at src/config.rs:1930:17
   8: stacks_node::config::Config::from_config_default
             at src/config.rs:936:13
   9: stacks_node::config::Config::from_config_file
             at src/config.rs:880:13
  10: stacks_node::config::Config::get_miner_config
             at src/config.rs:540:26
  11: stacks_node::run_loop::neon::RunLoop::drive_pox_reorg_stacks_block_processing
             at src/run_loop/neon.rs:680:28
      stacks_node::run_loop::neon::RunLoop::drive_chain_liveness
             at src/run_loop/neon.rs:956:13
  12: stacks_node::run_loop::neon::RunLoop::spawn_chain_liveness_thread::{{closure}}
             at src/run_loop/neon.rs:990:17
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
      std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
      std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  15: start_thread
             at ./nptl/pthread_create.c:442:8
  16: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Dumping core for pid 2060764
Quit (core dumped)
```

### LINKED ISSUE #4427: Stacks node panic when ctrl-c'd
Another "hit and miss" panic, this time during a graceful shutdown via Ctrl-C during sync-startup.

Low prio, just documenting that it happened.

```log
     Running `/home/cylwit/Code/github.com/stacks-network/stacks-blockchain/target/debug/stacks-node start --config ./conf/mainnet-follower-conf.toml`
INFO [1708886495.679664] [testnet/stacks-node/src/main.rs:296] [main] stacks-node 0.1.0 (:, debug build, linux [x86_64])
INFO [1708886495.679692] [testnet/stacks-node/src/main.rs:358] [main] Loading config at path ./conf/mainnet-follower-conf.toml
WARN [1708886495.809265] [stackslib/src/chainstate/coordinator/mod.rs:3438] [main] Sortition DB /tmp/stacks-node-1708886495679/mainnet/burnchain/sortition does not exist; assuming it will be instantiated with the correct version
WARN [1708886495.809294] [stackslib/src/chainstate/coordinator/mod.rs:3454] [main] Chainstate DB /tmp/stacks-node-1708886495679/mainnet/chainstate does not exist; assuming it will be instantiated with the correct version
INFO [1708886495.809305] [testnet/stacks-node/src/run_loop/neon.rs:430] [main] Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
WARN [1708886495.809321] [stackslib/src/burnchains/burnchain.rs:684] [main] Failed to stat burnchain DB path '/tmp/stacks-node-1708886495679/mainnet/burnchain/burnchain.sqlite': Os { code: 2, kind: NotFound, message: "No such file or directory" }
WARN [1708886496.432428] [stackslib/src/burnchains/bitcoin/indexer.rs:427] [main] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
INFO [1708886497.976872] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.2% (2000 out of 832017)
INFO [1708886498.164964] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.5% (4000 out of 832017)
INFO [1708886498.513875] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.7% (6000 out of 832017)
INFO [1708886498.853279] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.0% (8000 out of 832017)
INFO [1708886499.239032] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.2% (10000 out of 832017)
INFO [1708886499.834963] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.4% (12000 out of 832017)
INFO [1708886500.455101] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.7% (14000 out of 832017)
INFO [1708886501.051108] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.9% (16000 out of 832017)
INFO [1708886501.564699] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.2% (18000 out of 832017)
INFO [1708886502.300368] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.4% (20000 out of 832017)
^CGraceful termination request received (signal `CtrlC`), will complete the ongoing runloop cycles and terminate
INFO [1708886502.796622] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.6% (22000 out of 832017)
ERRO [1708886502.845878] [stackslib/src/burnchains/burnchain.rs:627] [main] Failed to sync initial headers
ERRO [1708886502.946107] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:543] [main] Unable to sync with burnchain: Try synchronizing again
ERRO [1708886502.946154] [testnet/stacks-node/src/run_loop/neon.rs:454] [main] Burnchain controller stopped: ChainsCoordinator closed
ERRO [1708886502.946186] [testnet/stacks-node/src/main.rs:273] [main] Process abort due to thread panic: panicked at testnet/stacks-node/src/run_loop/neon.rs:455:17:
explicit panic
ERRO [1708886503.246361] [testnet/stacks-node/src/main.rs:275] [main] Panic backtrace:    0: stacks_node::main::{{closure}}
             at src/main.rs:274:18
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
      core::panicking::panic_explicit
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:179:5
   7: stacks_node::run_loop::neon::RunLoop::instantiate_burnchain_state::panic_cold_explicit
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic.rs:87:13
   8: stacks_node::run_loop::neon::RunLoop::instantiate_burnchain_state
             at src/run_loop/neon.rs:455:17
   9: stacks_node::run_loop::neon::RunLoop::start
             at src/run_loop/neon.rs:1010:29
  10: stacks_node::main
             at src/main.rs:452:9
  11: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  12: std::rt::lang_start::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  14: main
  15: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  17: _start

Dumping core for pid 53427
```

### PR DESCRIPTION
**Pull request by 8marz8**
### Description
There are already signal handlers and flags in place for handling graceful shutdown, but not prior to burnchain sync. This PR propagates an error if a Ctrl-C signal was submitted during burnchain sync instead of panicking.

In the case of network loss while adding bootstrap nodes, it applies a fixed retry before panicking.

### Applicable issues
- fixes #4427
- fixes #4423 

### Additional info (benefits, drawbacks, caveats)
This PR does not aim to eliminate panics. It only handles the specific cases mentioned in above issues. 

### Logs
Ctrl-C:

> Running `/Users/marzi/Projects/graceful-shutdown/stacks-core/target/debug/stacks-node start --config ./conf/mainnet-follower-conf.toml`
> INFO [1709428155.649663] [testnet/stacks-node/src/main.rs:295] [main] stacks-node 0.1.0 (:, debug build, macos [aarch64])
> INFO [1709428155.649798] [testnet/stacks-node/src/main.rs:357] [main] Loading config at path ./conf/mainnet-follower-conf.toml
> WARN [1709428156.429226] [stackslib/src/chainstate/coordinator/mod.rs:3439] [main] Sortition DB /tmp/stacks-node-1709428155650/mainnet/burnchain/sortition does not exist; assuming it will be instantiated with the correct version
> WARN [1709428156.429261] [stackslib/src/chainstate/coordinator/mod.rs:3455] [main] Chainstate DB /tmp/stacks-node-1709428155650/mainnet/chainstate does not exist; assuming it will be instantiated with the correct version
> INFO [1709428156.429278] [testnet/stacks-node/src/run_loop/neon.rs:430] [main] Start syncing Bitcoin headers, feel free to grab a cup of coffee, this can take a while
> WARN [1709428156.429294] [stackslib/src/burnchains/burnchain.rs:664] [main] Failed to stat burnchain DB path '/tmp/stacks-node-1709428155650/mainnet/burnchain/burnchain.sqlite': Os { code: 2, kind: NotFound, message: "No such file or directory" }
> INFO [1709428156.644475] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.2% (2000 out of 832891)
> INFO [1709428156.844205] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.5% (4000 out of 832891)
> WARN [1709428156.865688] [stackslib/src/burnchains/bitcoin/indexer.rs:426] [main] Unhandled error while receiving a message: Io(Custom { kind: ConnectionReset, error: "I/O error when processing message" })
> INFO [1709428157.186218] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 0.7% (6000 out of 832891)
> INFO [1709428157.565523] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.0% (8000 out of 832891)
> INFO [1709428157.838768] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.2% (10000 out of 832891)
> INFO [1709428158.142795] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.4% (12000 out of 832891)
> INFO [1709428158.405623] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.7% (14000 out of 832891)
> INFO [1709428158.678508] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 1.9% (16000 out of 832891)
> INFO [1709428158.940691] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.2% (18000 out of 832891)
> INFO [1709428159.259745] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.4% (20000 out of 832891)
> ^CGraceful termination request received (signal `CtrlC`), will complete the ongoing runloop cycles and terminate
> INFO [1709428159.530655] [stackslib/src/burnchains/bitcoin/spv.rs:1286] [main] Syncing Bitcoin headers: 2.6% (22000 out of 832891)
> ERRO [1709428159.535641] [stackslib/src/burnchains/burnchain.rs:607] [main] Failed to sync initial headers
> ERRO [1709428159.635821] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:543] [main] Unable to sync with burnchain: Try synchronizing again
> INFO [1709428159.635895] [testnet/stacks-node/src/run_loop/neon.rs:457] [main] Shutdown initiated during burnchain initialization: ChainsCoordinator closed
> INFO [1709428159.636016] [testnet/stacks-node/src/run_loop/neon.rs:1030] [main] Exiting stacks-node
> 

Network connectivity loss during `add_bootstrap_node`:

> NFO [1709427268.387854] [testnet/stacks-node/src/main.rs:295] [main] stacks-node 0.1.0 (:, debug build, macos [aarch64])
> INFO [1709427268.387963] [testnet/stacks-node/src/main.rs:357] [main] Loading config at path ./conf/mainnet-follower-conf.toml
> INFO [1709427268.435543] [testnet/stacks-node/src/config.rs:942] [main] About to call set_bootstrap_nodes
> INFO [1709427268.435614] [testnet/stacks-node/src/config.rs:1931] [main] about to sleep before hostport.to_socket_addrs
> ERRO [1709427278.443863] [testnet/stacks-node/src/config.rs:1952] [main] Attempt 1 - Failed to resolve 'seed.mainnet.hiro.so:20444': failed to lookup address information: nodename nor servname provided, or not known. Retrying in 2s...
> ERRO [1709427280.446148] [testnet/stacks-node/src/config.rs:1952] [main] Attempt 2 - Failed to resolve 'seed.mainnet.hiro.so:20444': failed to lookup address information: nodename nor servname provided, or not known. Retrying in 4s...
> ERRO [1709427284.451537] [testnet/stacks-node/src/config.rs:1952] [main] Attempt 3 - Failed to resolve 'seed.mainnet.hiro.so:20444': failed to lookup address information: nodename nor servname provided, or not known. Retrying in 8s...
> ERRO [1709427292.454097] [testnet/stacks-node/src/config.rs:1952] [main] Attempt 4 - Failed to resolve 'seed.mainnet.hiro.so:20444': failed to lookup address information: nodename nor servname provided, or not known. Retrying in 16s...
> ERRO [1709427308.456645] [testnet/stacks-node/src/config.rs:1952] [main] Attempt 5 - Failed to resolve 'seed.mainnet.hiro.so:20444': failed to lookup address information: nodename nor servname provided, or not known. Retrying in 32s...
> ERRO [1709427340.462413] [testnet/stacks-node/src/main.rs:272] [main] Process abort due to thread panic: panicked at testnet/stacks-node/src/config.rs:1950:25:
> Failed to resolve 'seed.mainnet.hiro.so:20444' after 5 attempts: failed to lookup address information: nodename nor servname provided, or not known
> ERRO [1709427340.523360] [testnet/stacks-node/src/main.rs:274] [main] Panic backtrace:    0: backtrace::backtrace::libunwind::trace
>              at /Users/marzi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/libunwind.rs:93:5
>       backtrace::backtrace::trace_unsynchronized
>              at /Users/marzi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:66:5
>       backtrace::backtrace::trace
>              at /Users/marzi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/backtrace/mod.rs:53:14
>       backtrace::capture::Backtrace::create
>              at /Users/marzi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:176:9
>    1: backtrace::capture::Backtrace::new
>              at /Users/marzi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.69/src/capture.rs:140:22
>    2: stacks_node::main::{{closure}}
>              at src/main.rs:273:18
>    3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
>       std::panicking::rust_panic_with_hook
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
>    4: std::panicking::begin_panic_handler::{{closure}}
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
>    5: std::sys_common::backtrace::__rust_end_short_backtrace
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
>    6: rust_begin_unwind
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
>    7: core::panicking::panic_fmt
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
>    8: stacks_node::config::NodeConfig::add_bootstrap_node
>              at src/config.rs:1950:25
>       stacks_node::config::NodeConfig::set_bootstrap_nodes
>              at src/config.rs:1983:17
>    9: stacks_node::config::Config::from_config_default
>              at src/config.rs:943:13
>   10: stacks_node::config::Config::from_config_file
>              at src/config.rs:886:13
>   11: stacks_node::main
>              at src/main.rs:425:22
>   12: core::ops::function::FnOnce::call_once
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
>       std::sys_common::backtrace::__rust_begin_short_backtrace
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
>   13: std::rt::lang_start::{{closure}}
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
>   14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
>       std::panicking::try::do_call
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
>       std::panicking::try
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
>       std::panic::catch_unwind
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
>       std::rt::lang_start_internal::{{closure}}
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
>       std::panicking::try::do_call
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
>       std::panicking::try
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
>       std::panic::catch_unwind
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
>       std::rt::lang_start_internal
>              at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
>   15: _main

### CODE REVIEW

**Review by jcnelson — APPROVED** [review]

**Review by jferrant — APPROVED** [review]

File: testnet/stacks-node/src/config.rs [hunk 1]
```diff
@@ -1927,7 +1927,42 @@ impl NodeConfig {
         let pubkey = Secp256k1PublicKey::from_hex(pubkey_str)
             .unwrap_or_else(|_| panic!("Invalid public key '{pubkey_str}'"));
         debug!("Resolve '{}'", &hostport);
-        let sockaddr = hostport.to_socket_addrs().unwrap().next().unwrap();
+
+        let mut attempts = 0;
+        let max_attempts = 5;
+        let mut delay = Duration::from_secs(2);
```
Comment (netrome) [inline testnet/stacks-node/src/config.rs:1933]: Nit: It feels a bit weird to me to hard-code these parameters here. I would be more happy to see a solution which breaks out the retry logic to a separate function, similar to `https://docs.rs/retry/2.0.0/retry/` while allowing the user to configure the retry.

Not sure if it's worth the effort though, but it would be nice to have this testable and tested in the code which the current change doesn't seem to be.

Comment (8marz8) [reply testnet/stacks-node/src/config.rs:1933]: sure, I can make it optionally configurable if it's okay for me to expand `NodeConfigFile`
As for testing it, I wouldn't be so sure since I tested it manually by just turning off my wifi before that method gets called.

Comment (netrome) [reply testnet/stacks-node/src/config.rs:1933]: Yeah `NodeConfigFile` looks like a good home for a potential `network_retry_timeout` parameter (just a single parameter in my opinion from which the `attempts`, `max_attempts` and `delay` can be derived). Although that's debatable, so perhaps best would be to merge this as-is since it's already got the necessary approvals and do that work as a follow-up if there's time and interest.

Comment (netrome) [reply testnet/stacks-node/src/config.rs:1933]: > As for testing it, I wouldn't be so sure since I tested it manually by just turning off my wifi before that method gets called.

Yeah that's what I suspected. I don't see any straightforward way to make the Ctrl-C shutdown logic testable given how the code is currently structured, so I guess that'll have to do for now.

Comment (8marz8) [reply testnet/stacks-node/src/config.rs:1933]: Cool, will ask @jferrant to merge after the rebase finishes.
