### PR TITLE
Fix/4752

### LINKED ISSUE #4752: Deprecate or remove (EDIT(jcnelson): or fix) the `/v2/fees/transfer` endpoint
## Problem

Everyone should be using the `/v2/fees/transaction` for fee estimation. Unfortunately, not only does the `/v2/fees/transfer` endpoint still exist, it isn't even marked deprecated anywhere clearly (e.g. not in the [openapi spec](https://github.com/stacks-network/stacks-core/blob/master/docs/rpc/openapi.yaml), not in [this doc](https://github.com/stacks-network/stacks-core/blob/master/docs/rpc-endpoints.md#get-v2feestransfer), not in the [code](https://github.com/stacks-network/stacks-core/blob/master/stackslib/src/net/api/getstxtransfercost.rs) )

This routinely confuses people, not least because looking at the endpoints alone (`/v2/fees/transfer` vs `/v2/fees/transaction`) it's impossible to tell the different without looking at the docs or code.

## Desired solution

Deprecate or better yet, remove the outdated `/v2/fees/transfer` endpoint.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #4752 by having `/v2/fees/transfer` report the median transaction fee estimate for a STX-transfer of 180 bytes (the size of a single-sig unsponsored STX transfer).  The caller can supply the `?length=xxx` query parameter to set an alternative length, if desired.

### CODE REVIEW

File: stackslib/src/net/api/getstxtransfercost.rs [hunk 1]
```diff
@@ -92,9 +119,58 @@ impl RPCRequestHandler for RPCGetStxTransferCostRequestHandler {
...
+            .take()
+            .ok_or(NetError::SendError("`estimated_len` not set".into()))?;
+
+        let fee_resp = node.with_node_state(|_network, sortdb, _chainstate, _mempool, rpc_args| {
+            let tip = self.get_canonical_burn_chain_tip(&preamble, sortdb)?;
+            let stacks_epoch = self.get_stacks_epoch(&preamble, sortdb, tip.block_height)?;
+
+            if let Some((_, fee_estimator, metric)) = rpc_args.get_estimators_ref() {
+                // STX transfer transactions have zero runtime cost
+                let estimated_cost = ExecutionCost::zero();
```
Comment (obycode) [inline stackslib/src/net/api/getstxtransfercost.rs:133]: I think they do have a non-zero cost. From costs-3:

```
(define-read-only (cost_stx_transfer (n uint))
    {
        runtime: u4640,
        write_length: u1,
        write_count: u1,
        read_count: u1,
        read_length: u1
    })
```

File: stackslib/src/net/api/getstxtransfercost.rs [hunk 2]
```diff
@@ -92,9 +119,58 @@ impl RPCRequestHandler for RPCGetStxTransferCostRequestHandler {
...
+                            "Logic error in fee estimation: did not get three estimates".into(),
+                        ),
+                    ));
+                }
+
+                // safety -- checked estimations.len() == 3 above
+                let median_estimation = &estimations[1];
+
+                // NOTE: this returns the fee _rate_
+                Ok(median_estimation.fee / estimated_len)
```
Comment (obycode) [inline stackslib/src/net/api/getstxtransfercost.rs:158]: This fee / byte rate does seem to match what the previous implementation did, but I'm not sure how meaningful that value is or if users know how to use that rate properly. I'd definitely like to hear input from users of this endpoint (wallets) on this.

Comment (jcnelson) [reply stackslib/src/net/api/getstxtransfercost.rs:158]: The [documentation](https://github.com/stacks-network/stacks-core/blob/master/docs/rpc-endpoints.md#get-v2feestransfer) says its a fee per byte.

That said, I'm regretting the `length=` query parameter, since it won't even be used.  I'll just take that out.

File: stackslib/src/net/api/getstxtransfercost.rs (hunk 1 above)
Comment (jcnelson) [reply stackslib/src/net/api/getstxtransfercost.rs:133]: That's for the Clarity function `(stx-transfer? ..)`.  The bare STX-transfer transaction has zero runtime cost, since it directly calls `stx_transfer_consolidated()` via an `Environment` (which only consumes VM memory, not runtime).

You can see for yourself as follows.  Consider the STX-transfer handling code:

```rust
let cost_before = clarity_tx.cost_so_far();
let (value, _asset_map, events) = clarity_tx
    .run_stx_transfer(
        &origin_account.principal,
        addr,
        u128::from(*amount),
        &BuffData {
            data: Vec::from(memo.0.clone()),
        },
    )
    .map_err(Error::ClarityError)?;

let mut total_cost = clarity_tx.cost_so_far();
total_cost
    .sub(&cost_before)
    .expect("BUG: total block cost decreased");

let receipt = StacksTransactionReceipt::from_stx_transfer(
    tx.clone(),
    events,
    value,
    total_cost,
);
Ok(receipt)
```
And here's a sample receipt pulled from mainnet (note the execution cost fields -- they're all 0):

```
    {
      "tx_id": "0x5d40b24095eb0282b2f25fcc8bae8c639a636ca85d9b97878e3123655bda5c83",
      "nonce": 3340,
      "fee_rate": "300",
      "sender_address": "SP16242W0FA64J0HSAB866XK1XPBWFBX4HNRPXSRX",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [],
      "anchor_mode": "any",
      "is_unanchored": false,
      "block_hash": "0xf0d51285860650e6590b519977bf6087f9a6c98d75ceeffe4ac13c58f76f9dc9",
      "parent_block_hash": "0x4aabb7c0f31bc1ec13b42f61ddb5d430702843d2e69c96d652b7ff51d333848a",
      "block_height": 149171,
      "block_time": 1715102709,
      "block_time_iso": "2024-05-07T17:25:09.000Z",
      "burn_block_time": 1715102652,
      "burn_block_time_iso": "2024-05-07T17:24:12.000Z",
      "parent_burn_block_time": 1715102607,
      "parent_burn_block_time_iso": "2024-05-07T17:23:27.000Z",
      "canonical": true,
      "tx_index": 385,
      "tx_status": "success",
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "microblock_hash": "0x",
      "microblock_sequence": 2147483647,
      "microblock_canonical": true,
      "event_count": 1,
      "events": [],
      "execution_cost_read_count": 0,
      "execution_cost_read_length": 0,
      "execution_cost_runtime": 0,
      "execution_cost_write_count": 0,
      "execution_cost_write_length": 0,
      "tx_type": "token_transfer",
      "token_transfer": {
        "recipient_address": "SP3WFJ0FT70HXVHS36C8WHFEVN6SRAT5P1B2MN4HC",
        "amount": "1",
        "memo": "0x6d627272723130300000000000000000000000000000000000000000000000000000"
      }
    },
```

Comment (obycode) [reply stackslib/src/net/api/getstxtransfercost.rs:133]: Oh interesting, thanks for that. I forgot that was treated differently. I guess we talked about this before when we were discussing how STX-20 transfers were unfairly cheap.

**Review by obycode — APPROVED** [review]
LGTM!

**Comment by jcnelson** [comment]
ping @kantai

**Review by kantai — APPROVED** [review]
