### PR TITLE
fix: `/v3/health` use canonical stacks height header

### LINKED ISSUE #6318: [Bug] /v3/health always fails with HTTP 500
**Describe the bug**
All attempts to query `/v3/health` fail with HTTP 500 and the message `Couldn't obtain stats on any bootstrap peers, unable to determine health.`

**Steps To Reproduce**

```bash
$ curl http://localhost:20443/v3/health
Couldn't obtain stats on any bootstrap peers, unable to determine health.$
```

**Expected behavior**
I expect the health JSON to be returned with HTTP 200

**Environment (please complete the following information):**
 - OS: Alpine Linux 3.21
 - Rust version: 1.88
 - Version of the appropriate binary / software package: 3.1.0.0.13 (`release/3.1.0.0.13`)

**Additional context**
I have verified that my node is connected to at least three of the bootstrap peers configured.

```bash
$ for host in $(cat mainnet.toml | grep -E '^bootstrap_node' | tr -d ' "' | sed -r 's/^bootstrap_node=//g' | sed -r 's/[0-9a-f]+@([^:]+):([0-9]+)/\1/g' | tr ',' ' '); do drill "$host" | grep -E "^${host}" | awk '{print $5}' | tee -a /tmp/seed-nodes.txt; done
34.150.184.50
3.122.176.89
52.77.118.154
54.91.222.127
$ for ip in $(cat /tmp/seed-nodes.txt); do curl -sL http://localhost:20443/v2/neighbors | jq '.outbound[].ip' | grep "$ip"; done
"34.150.184.50"
"3.122.176.89"
"52.77.118.154"
```

It is possible that my node has never instantiated an unconfirmed tenure downloader to these nodes, which would lead to `NakamotoDownloadStateMachine::get_max_stacks_height_of_neighbors()` evaluating to `None`.  There should be a fallback behavior, since my node has 46 outbound peers and is definitely fetching unconfirmed block data.

### PR DESCRIPTION
**Pull request by Jiloc**
This PR builds on top of #6344 and will remain in review until that one is merged.

Previously, the `/v3/health` endpoint relied on data from `NakamotoDownloadStateMachine`, which is consumed after evaluation. This led to inconsistent behavior: during syncing, the endpoint worked correctly, but once the node reached chaintip, the necessary data was often already consumed, resulting in missing neighbor info and a 500 error.

This PR introduces a new approach builds on top of the changes in #6344, which ensure that all RPC endpoints include the `X-Canonical-Stacks-Tip-Height` header in their responses. Now, the node caches the highest tip received from neighbors during normal operations and uses that as the reference point for the `/v3/health` endpoint.

**Key changes:**

- Removed old logic and associated functions like `get_max_stacks_height_of_neighbors`.
- Instead of adding a dedicated 10-minute integration test with multiple nodes, I extended the existing `multiple_miner` test. This ensures that `ConversationHttp::chat` is called and that the peer height is updated correctly during normal operation.
- Updated `StacksNodeState::canonical_stacks_tip_height` to return `PeerNetwork::stacks_tip.height` instead of `PeerNetwork::burnchain_tip.stacks_block_height`.

To validate the reliability, I analyzed the logs from a mainnet node at chaintip over the past 24 hours. I measured how often it receives responses from peers 

--- Request Time Interval Analysis (Last 24 Hours) ---
Average Time: 6.4775 seconds
Minimum Time: 0.0002 seconds
Maximum Time: 55.2894 seconds
Standard Deviation: 8.1859
Total Intervals Found: 13,440

This suggests the new method won't always have the absolute latest tip but provides a close and stable approximation.

### Applicable issues

- fixes #6318

### Checklist

- [x] Test coverage for new or modified code paths
- [ ] Changelog is updated
- [x] Required documentation changes (e.g., `docs/rpc/openapi.yaml` and `rpc-endpoints.md` for v2 endpoints, `event-dispatcher.md` for new events)
- [ ] New clarity functions have corresponding PR in `clarity-benchmarking` repo
- [ ] New integration test(s) added to `bitcoin-tests.yml`

### CODE REVIEW

File: stackslib/src/net/mod.rs [hunk 1]
```diff
@@ -692,10 +693,8 @@ impl<'a> StacksNodeState<'a> {
         res
     }
 
-    pub fn canonical_stacks_tip_height(&mut self) -> u32 {
-        self.with_node_state(|network, _, _, _, _| {
-            network.burnchain_tip.canonical_stacks_tip_height as u32
-        })
+    pub fn canonical_stacks_tip_height(&mut self) -> u64 {
+        self.with_node_state(|network, _, _, _, _| network.stacks_tip.height)
```
Comment (Jiloc) [inline stackslib/src/net/mod.rs]: @jcnelson I initially used `network.burnchain_tip.canonical_stacks_tip_height` here, as you suggested. However, during integration tests (e.g. multiple_miners), I found out that `burnchain_tip.canonical_stacks_tip_height` always lagged behind. in the `multiple_miners` tests it always stops at 121 compared to `stacks_tip.height` that arrives at 128 at the end of the test.
I must be missing a step in the test to properly trigger the refresh.

For now, I’ve used `network.stacks_tip.height`, as it matches the expected value and is also used in `/v2/info`.

I'm absolutely open to reverting this to use `burnchain_tip` if someone has insight on how to consistently trigger its update in integration tests.

Comment (jcnelson) [reply stackslib/src/net/mod.rs]: I looked at the code some more, and I agree with your change.  I don't think `network.burnchain_tip.canonical_stacks_tip_height` is used in Nakamoto, nor is it even meaningful.  The code which memoizes the canonical Stacks tip on the sortition tip is not called in processing Nakamoto sortitions.  I had forgotten that we changed how this works when we last spoke.  Your use of `stacks_tip.height` is correct.

File: stackslib/src/net/api/gethealth.rs [hunk 2]
```diff
@@ -156,97 +102,26 @@ impl RPCRequestHandler for RPCGetHealthRequestHandler {
...
-                None => create_error_response(
-                    &preamble,
-                    "Couldn't obtain stats on any bootstrap peers, unable to determine health.",
-                ),
-            }
-        })
+        let preamble = HttpResponsePreamble::ok_json(&preamble);
+        let data = RPCGetHealthResponse {
+            difference_from_max_peer,
+            max_stacks_height_of_neighbors,
```
Comment (jcnelson) [inline stackslib/src/net/api/gethealth.rs:125]: Do you think you could also track and report the IP and port number of the peer which reported the max height?  This would be very useful when diagnosing why the local view of the maximum Stacks block height is off.

File: stackslib/src/net/mod.rs (hunk 1 above)
Comment (Jiloc) [reply stackslib/src/net/mod.rs]: Thanks for confirming! Would it make sense to track this as technical debt in an issue? We should evaluate whether any code path in Nakamoto is incorrectly using `burnchain_tip.canonical_stacks_tip_height`, or consider removing it entirely if it’s irrelevant for epoch 2.x. I worry that having multiple similar fields could trip up devs in the future

Comment (jcnelson) [reply stackslib/src/net/mod.rs]: I've already checked -- `burnchain_tip.canonical_stacks_tip_height` is used for Stacks 2.x code paths.  Perhaps they can be changed.

**Comment by jcnelson** [comment]
Looks like some of your tests are failing.

File: stackslib/src/net/api/gethealth.rs (hunk 2 above)
Comment (Jiloc) [reply stackslib/src/net/api/gethealth.rs:125]: implemented in https://github.com/stacks-network/stacks-core/pull/6347/commits/2ad62bc7b936272ad23b446720c6223d8df85447

File: stackslib/src/net/api/gethealth.rs [hunk 3]
```diff
@@ -156,97 +104,29 @@ impl RPCRequestHandler for RPCGetHealthRequestHandler {
...
-                        }
-                        None => {
-                            return create_error_response(
-                                &preamble,
-                                "Nakamoto block downloader not found (Epoch 3.0+), unable to determine health.",
-                            );
-                        }
-                    }
-                }
+        let (max_stacks_height_of_neighbors, node_stacks_tip_height) =
```
Comment (jcnelson) [inline stackslib/src/net/api/gethealth.rs]: Nit:

```rust
let ((max_stacks_neighbor_address, max_stacks_height_of_neighbors), node_stacks_tip_height) =
   node.with_node_state(|network, _sortdb, _chainstate, _mempool, _rpc_args| {
      (
         network.highest_stacks_neighbor
            .map(|(addr, height)| (Some(addr.to_string()), height))
            .unwrap_or((None, 0)),
         network.stacks_tip.height
      )
   });
```

**Review by jcnelson — APPROVED** [review]
LGTM, but please address the nit before merging. Thanks!

**Review by fdefelici — COMMENTED** [review]
LGMT!

Waiting for the nit to be addressed before providing final approval

File: stackslib/src/net/api/gethealth.rs (hunk 3 above)
Comment (Jiloc) [reply stackslib/src/net/api/gethealth.rs]: addressed in https://github.com/stacks-network/stacks-core/pull/6347/commits/e4c57fb1d4fae32135d9d02439e31d91e9e1d46b

**Comment by Jiloc** [comment]
QQ for both of you: I’ve already been bitten a couple of times by my own assumptions about how this endpoint gets the information (first I was extracting the chaintip from unconfirmed tenures only, then I added confirmed ones… both times I was solving the wrong problem). Tests were passing, but they didn’t really reflect real operations.

For the previous PRs I could have catched this by running the updates on a synced node, but in this case I can’t since the canonical chaintip header isn’t yet released on the operational nodes.

For this PR, I validated the approach by:

- a more robust check into the `multiple_miners` integration test
- checking how often a node receives RPC responses in a real mainnet envirnoment (which always include the peers’ chaintip eventually).

Do you think that’s solid enough validation, or would you suggest adding anything else?

**Comment by fdefelici** [comment]
> QQ for both of you: I’ve already been bitten a couple of times by my own assumptions about how this endpoint gets the information (first I was extracting the chaintip from unconfirmed tenures only, then I added confirmed ones… both times I was solving the wrong problem). Tests were passing, but they didn’t really reflect real operations.
> 
> For the previous PRs I could have catched this by running the updates on a synced node, but in this case I can’t since the canonical chaintip header isn’t yet released on the operational nodes.
> 
> For this PR, I validated the approach by:
> 
> * a more robust check into the `multiple_miners` integration test
> * checking how often a node receives RPC responses in a real mainnet envirnoment (which always include the peers’ chaintip eventually).
> 
> Do you think that’s solid enough validation, or would you suggest adding anything else?

Actually I'm fine with this. Aside from running on a live network, this seems like the most thorough validation we can do at this stage.

**Comment by jcnelson** [comment]
> Do you think that’s solid enough validation, or would you suggest adding anything else?

I think that's fine for now.
