### PR TITLE
Miner metrics and mock miner improvements

### LINKED ISSUE #6172: Mock miner not mining sometimes
I'm not yet sure of the cause, but I noticed that sometimes, the mock miner will fail to mine blocks for a period of time, then randomly come back. For example, looking at Hiro's mock-miner logs from 6/4/2025, 15:30 - 18:30 UTC, and searching for "Miner: Assembled block", we can see these gaps:

Image

The large gap begins when burn block 899792 arrives and ends after block 899795 arrives.

### PR DESCRIPTION
**Pull request by obycode**
This adds a new prometheus metric `stacks_node_miner_stop_reason_total` to track why a miner stopped mining a block, with the main goal of making it easier to track when the mempool is empty.

This also fixes #6172 -- various problems when mock-mining.

### CODE REVIEW

File: stackslib/src/monitoring/mod.rs [hunk 1]
```diff
@@ -462,6 +462,33 @@ pub fn get_burnchain_signer() -> Option<BurnchainSigner> {
     None
 }
 
+pub enum MinerStopReason {
+    NoTransactions,
+    Preempted,
+    LimitReached,
+    DeadlineReached,
+}
```
Comment (hstove) [inline stackslib/src/monitoring/mod.rs]:
```suggestion
define_named_enum!(MinerStopReason {
    NoTransactions("no_transactions"),
    Preempted("preempted"),
    LimitReached("limit_reached"),
    DeadlineReached("deadline_reached"),
});
```

**Review by hstove — DISMISSED** [review]
LGTM!

**Review by kantai — APPROVED** [review]
