### PR TITLE
Fix/5044

### LINKED ISSUE #5044: [Network] fork-aware inventory cache
The caching logic for inventory sortitions needs to be aware of the fact that some cached data is only relevant in some forks.  Failure to address this leads to nodes reporting incorrect inventory data, and confusing downstream nodes.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #5044 by making a fork-aware cache for inventory data -- namely, cached sortitions we had to load, and cached per-fork tenures.  See tests and doc strings for how it works.

### CODE REVIEW

File: stackslib/src/net/inv/nakamoto.rs [hunk 1]
```diff
@@ -105,33 +105,149 @@ impl InvTenureInfo {
...
+    /// new tip instead of reloading them from disk each time.
+    ///
+    /// However, searching for an ancestor tip incurs a sqlite DB read, so we want to bound the
+    /// search depth.  In practice, the bound on this depth would be derived from how often the
+    /// chain tip changes relative to how often we serve up inventory data.  The depth should be
+    /// the maximum expected number of blocks to be processed in-between handling `GetNakamotoInv`
+    /// messages.
+    ///
+    /// If found, then return the ancestor block ID represented in `self.processed_tenures`.
+    /// If not, then reutrn None.
```
Comment (obycode) [inline stackslib/src/net/inv/nakamoto.rs:153]:
```suggestion
    /// If not, then return None.
```

**Review by obycode — COMMENTED** [review]
This looks good. Just had some very minor comments.

File: stackslib/src/chainstate/stacks/db/accounts.rs [hunk 2]
```diff
@@ -385,11 +415,19 @@ impl StacksChainState {
     ) {
         clarity_tx
             .with_clarity_db(|ref mut db| {
-                let next_nonce = cur_nonce.checked_add(1).expect("OUT OF NONCES");
+                let next_nonce = cur_nonce
+                    .checked_add(1)
+                    .unwrap_or_else(|| panic!("OUT OF NONCES"));
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply stackslib/src/chainstate/stacks/db/accounts.rs]: Fixed

File: stackslib/src/net/inv/nakamoto.rs [hunk 3]
```diff
@@ -105,33 +105,149 @@ impl InvTenureInfo {
...
+                    .insert(tip_block_id.clone(), HashMap::new());
+            }
+        }
+
+        let Some(tenure_infos) = self.processed_tenures.get_mut(tip_block_id) else {
+            unreachable!("FATAL: inserted table for chain tip, but didn't get it back");
+        };
+
+        // this tip has a known table
+        if let Some(loaded_tenure_info) = tenure_infos.get_mut(tenure_id_consensus_hash) {
```
Comment (kantai) [inline stackslib/src/net/inv/nakamoto.rs:221]: I think you can use `get()` instead of `get_mut()` here.

File: stackslib/src/net/inv/nakamoto.rs [hunk 4]
```diff
@@ -105,33 +105,149 @@ impl InvTenureInfo {
...
+                    .remove(&ancestor_tip_id)
+                    .unwrap_or_else(|| {
+                        panic!("FATAL: did not have ancestor tip reported by search");
+                    });
+
+                self.processed_tenures
+                    .insert(tip_block_id.clone(), ancestor_tenures);
+            } else {
+                self.processed_tenures
+                    .insert(tip_block_id.clone(), HashMap::new());
```
Comment (kantai) [inline stackslib/src/net/inv/nakamoto.rs:212]: Should `processed_tenures` garbage collect? Otherwise, it seems like it might grow unbounded with the number of forks (which admittedly should be small, but its probably worth doing some limited GC).

**Review by kantai — COMMENTED** [review]
This LGTM, just a couple comments

File: stackslib/src/net/inv/nakamoto.rs (hunk 4 above)
Comment (jcnelson) [reply stackslib/src/net/inv/nakamoto.rs:212]: It can't, because nodes can ask for any inventory vector from any reward cycle (and must do so if they are booting up).

We don't garbage-collect in the epoch 2.x inventory generator either, for the same reason.  It would only lead to thrashing when nodes ask for old inventories.

File: stackslib/src/net/inv/nakamoto.rs (hunk 3 above)
Comment (jcnelson) [reply stackslib/src/net/inv/nakamoto.rs:221]: Yup

**Review by obycode — APPROVED** [review]
LGTM!

**Review by kantai — APPROVED** [review]
