### PR TITLE
Fix/4826

### LINKED ISSUE #4826: [Nakamoto] Do not use the Sortition DB's preprocessed reward sets
In epoch 3.0, the Nakamoto chains coordinator will load the reward set from both the Nakamoto chainstate (in `OnChainRewardSetProvider::read_reward_set_nakamoto()`) and from the sortition DB (in `ChainsCoordinator::get_nakamoto_reward_cycle_info()`).  This is a bug waiting to happen -- we should only rely on a single source of truth for the reward set.  Instead, the coordinator should exclusively use the reward set information in the Nakamoto chain state.  The preprocessed reward sets in the sortition DB are only meant for epoch 2.x logic that needs access to the reward set prior to Nakamoto going live.

There are two things to do:

* The Nakamoto chains coordinator needs to rely exclusively on the Nakamoto chain state, except for the first-ever reward cycle (in which case, the reward set will only be available in the sortition DB).

* The PeerNetwork needs to load the reward cycle info from the Nakamoto chain state, and fall back to the sortition DB if the reward cycle's prepare phase happened in epoch 2.

### PR DESCRIPTION
**Pull request by jcnelson**
This fixes #4826 by consolidating the way in which the code loads a Nakamoto-epoch reward set.  It now will load it from the Nakamoto chain state, where it is keyed to the PoX anchor block selected in the given burnchain fork, with one exception:  the first-ever Nakamoto reward set must be loaded from the sortition DB, since that'll be the only place where it is available.

### CODE REVIEW

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs [hunk 1]
```diff
@@ -243,34 +238,151 @@ pub fn get_nakamoto_reward_cycle_info<U: RewardSetProvider>(
...
+    );
+
+    return Ok(Some(rc_info));
+}
+
+/// Helper to get the Nakamoto reward set for a given reward cycle.
+/// In all but the first Nakamoto reward cycle, this will load up the stored reward set from the
+/// Nakamoto chain state.  In the first Nakamoto reward cycle, where the reward set is computed
+/// from epoch2 state, the reward set will be loaded from the sortition DB (which is the only place
+/// it will be stored).
```
Comment (kantai) [inline stackslib/src/chainstate/nakamoto/coordinator/mod.rs:282]: I want to push back on this a little bit -- is `load_nakamoto_reward_set()` even invoked for the first nakamoto reward cycle? That reward cycle starts during epoch 2.5, so the 2.x reward set calculation should be used for it. If this is the case, I think we should be more direct about how `load_nakamoto_reward_set()` is invoked (maybe erroring if its invoked at a bad height?) and also remove the fallback-to-2x logic.

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs [hunk 2]
```diff
@@ -243,34 +238,151 @@ pub fn get_nakamoto_reward_cycle_info<U: RewardSetProvider>(
...
+///
+/// Returns Ok(Some((reward set info, PoX anchor block header))) on success
+/// Returns Ok(None) if the reward set is not yet known, but could be known by the time a
+/// subsequent call is made.
+pub fn load_nakamoto_reward_set<U: RewardSetProvider>(
+    burn_height: u64,
```
Comment (kantai) [inline stackslib/src/chainstate/nakamoto/coordinator/mod.rs:288]: The `burn_height` parameter in these methods is pretty confusing to me. It gets passed around between a bunch of different functions, and its not at all obvious what exactly its being used for. On closer inspection, it seems like it only ever gets used to compute the reward cycle number, but it is translated back and forth from burn height to reward cycle multiple times. In this method, for example, it's used to figure out what the _next_ reward cycle is (so, this method kind of implicitly assumes its being invoked during the prepare phase to load the next reward cycle's information), but before being passed onto `provider.get_reward_set_nakamoto()` its translated to the first block of the reward cycle, subtracted by 2, and gets passed directly to `read_reward_set_nakamoto()` which only ever uses it to invoke 

```rust
        let cycle = burnchain
            .block_height_to_reward_cycle(cycle_start_burn_height)
            .expect("FATAL: no reward cycle for burn height");
```

Which seems like it could lead to an off-by-one error for the reward cycle (i.e., `reward_cycle` in `load_nakamoto_reward_set` would return `n`, but  `read_reward_set_nakamoto` is using cycle `n-1` because of the `subtract(2)`).

I think it'd be much simpler if these methods just used `reward_cycle` as their parameter here, because the burn height is only ever used to calculate the reward cycle, so we can just set that directly.

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs [hunk 3]
```diff
@@ -243,34 +238,151 @@ pub fn get_nakamoto_reward_cycle_info<U: RewardSetProvider>(
...
-    let first_sortition_id = if let Some(first_sn) = prepare_phase_sortitions.first() {
-        if let Some(persisted_reward_cycle_info) =
-            SortitionDB::get_preprocessed_reward_set(sort_db.conn(), &first_sn.sortition_id)?
+    let first_epoch30_reward_cycle = burnchain
+        .next_reward_cycle(epoch_at_height.start_height)
+        .expect("FATAL: no reward cycle for epoch 3.0 start height");
+
+    if epoch_at_height.epoch_id < StacksEpochId::Epoch30
+        || (epoch_at_height.epoch_id == StacksEpochId::Epoch30
+            && reward_cycle == first_epoch30_reward_cycle)
```
Comment (kantai) [inline stackslib/src/chainstate/nakamoto/coordinator/mod.rs:316]: It'd be better for this epoch gating to be implemented via `epoch_id.uses_nakamoto_reward_set()` or similar. That way, the epoch "rules" all live in the `StacksEpochId` impl.

**Review by kantai — COMMENTED** [review]
This mostly looks good to me, my biggest comment is around the `burn_height` parameter: I think its kind of dangerous the way its currently used, and I'd much prefer at least the provider interface being more explicit about the reward cycle its fetching, but potentially all of the interfaces being more explicit as well (or, perhaps eliminating the parameter in `load_nakamoto_reward_set` and just using the `sortition_tip` to lookup the snapshot?)

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs (hunk 2 above)
Comment (jcnelson) [reply stackslib/src/chainstate/nakamoto/coordinator/mod.rs:289]: Sure, will do.

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs (hunk 3 above)
Comment (jcnelson) [reply stackslib/src/chainstate/nakamoto/coordinator/mod.rs:325]: Yup, can do

File: stackslib/src/chainstate/nakamoto/coordinator/mod.rs (hunk 1 above)
Comment (jcnelson) [reply stackslib/src/chainstate/nakamoto/coordinator/mod.rs]: >  is load_nakamoto_reward_set() even invoked for the first nakamoto reward cycle?

Yes, it is -- by both the chains coordinator and by the miner.  This function takes a reward cycle in the Nakamoto epoch, and returns its reward set.  The first Nakamoto reward cycle's reward set happens to have been generated in the last reward cycle for epoch 2.5, which is why there's a special-case path for it.

I'd prefer to keep it this way, and have one place where the special-case code path is reached, than to duplicate it into the half-dozen other places where it would become necessary if it was removed from this function.

Comment (kantai) [reply stackslib/src/chainstate/nakamoto/coordinator/mod.rs]: Okay, that works for me.

**Review by kantai — APPROVED** [review]

**Comment by jcnelson** [comment]
ping @obycode

**Review by obycode — APPROVED** [review]
Nice work! LGTM.

**Review by kantai — APPROVED** [review]

**Review by obycode — APPROVED** [review]
